<a href="https://colab.research.google.com/github/raheelam98/DataAnalysis/blob/main/EDA_Projects/Zameen_EDA_Project/NoteBook/Zameen_EDA_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Zameen.com**

In [1]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [2]:
#Mount Google Drive in Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#List Files in a Folder
!ls /content/drive/MyDrive/EDA/

ai_adoption_dataset.csv  cubic_zirconia.csv		    Scarped_Zameen.xlsx
bus_fare_dataset.csv	 pakistan_intellectual_capital.csv

In [4]:
import pandas as pd

# Correct path and filename
df = pd.read_excel('/content/drive/MyDrive/EDA/Scarped_Zameen.xlsx')

In [5]:
# modules we'll use
# import pandas as pd
import numpy as np

# helpful modules
import fuzzywuzzy # pip install fuzzywuzzy
from fuzzywuzzy import process

/usr/local/lib/python3.11/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

#### **Section : Data Understanding & Preprocessing**

In [6]:
df.head()

,Title,URL,City,Type,Area,Price,Purpose,Location,Description,Built in year,...,Nearby Schools,Nearby Hospitals,Nearby Shopping Malls,Nearby Restaurants,Distance From Airport (kms),Nearby Public Transport Service,Other Nearby Places,Maintenance Staff,Security Staff,Other Facilities
0,Hmr Waterfront 2 Bed Room Premium Apartment On...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,128 Sq. Yd.,PKR\n4.75 Crore,For Sale,"DHA Defence, Karachi, Sindh",SAIMA MARINA RESIDENCE HMR WATERFRONT\nINVESTO...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chance Deal! Luxury 2 Bedroom Seafront Apartme...,https://www.zameen.com/Property/dha_defence_dh...,Karachi,Flat,161 Sq. Yd.,PKR\n6.25 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n2 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Luxury 1 Bed At H& S Residence By Japanese Arc...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,111 Sq. Yd.,PKR\n3.45 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n1 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Luxury 1 Bed Seafront Apartment at HMR waterfr...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,106 Sq. Yd.,PKR\n2.98 Crore,For Sale,"DHA Defence, Karachi, Sindh",Chance Deal at HMR Waterfront 1-Bed Apartment ...,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2 Bed Apartment For Booking On 3 Years | Saima...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,156 Sq. Yd.,PKR\n4.65 Crore,For Sale,"DHA Defence, Karachi, Sindh",HMR WATERFRONT \n\nOwn Your Dream Apartment in...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Section 2: Data Understanding & Preprocessing
# 2) View basic info
# Dataset Info : Show index range, column types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18255 entries, 0 to 18254
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Title                            18239 non-null  object
 1   URL                              18255 non-null  object
 2   City                             18255 non-null  object
 3   Type                             18239 non-null  object
 4   Area                             18239 non-null  object
 5   Price                            18239 non-null  object
 6   Purpose                          18239 non-null  object
 7   Location                         18239 non-null  object
 8   Description                      14893 non-null  object
 9   Built in year                    11940 non-null  float64
 10  Parking Spaces                   9656 non-null   float64
 11  Double Glazed Windows            0 non-null      float64
 12  Central Air Conditioning         0 non-null      float64
 13  Central Heating                  0 non-null      float64
 14  Flooring                         0 non-null      float64
 15  Electricity Backup               0 non-null      float64
 16  Waste Disposal                   0 non-null      float64
 17  Floors                           8366 non-null   float64
 18  Other Main Features              0 non-null      float64
 19  Furnished                        0 non-null      float64
 20  Bedrooms                         18239 non-null  object
 21  Bathrooms                        18239 non-null  object
 22  Servant Quarters                 9657 non-null   float64
 23  Drawing Room                     0 non-null      float64
 24  Dining Room                      0 non-null      float64
 25  Kitchens                         13256 non-null  float64
 26  Study Room                       0 non-null      float64
 27  Prayer Room                      0 non-null      float64
 28  Powder Room                      0 non-null      float64
 29  Store Rooms                      9719 non-null   float64
 30  Steam Room                       0 non-null      float64
 31  Lounge or Sitting Room           0 non-null      float64
 32  Laundry Room                     0 non-null      float64
 33  Other Rooms                      0 non-null      float64
 34  Broadband Internet Access        0 non-null      float64
 35  Satellite or Cable TV Ready      0 non-null      float64
 36  Intercom                         0 non-null      float64
 37  Community Lawn or Garden         0 non-null      float64
 38  Community Swimming Pool          0 non-null      float64
 39  Community Gym                    0 non-null      float64
 40  First Aid or Medical Centre      0 non-null      float64
 41  Day Care Centre                  0 non-null      float64
 42  Kids Play Area                   0 non-null      float64
 43  Barbeque Area                    0 non-null      float64
 44  Mosque                           0 non-null      float64
 45  Community Centre                 0 non-null      float64
 46  Lawn or Garden                   0 non-null      float64
 47  Sauna                            0 non-null      float64
 48  Jacuzzi                          0 non-null      float64
 49  Nearby Schools                   0 non-null      float64
 50  Nearby Hospitals                 0 non-null      float64
 51  Nearby Shopping Malls            0 non-null      float64
 52  Nearby Restaurants               0 non-null      float64
 53  Distance From Airport (kms)      0 non-null      float64
 54  Nearby Public Transport Service  0 non-null      float64
 55  Other Nearby Places              0 non-null      float64
 56  Maintenance Staff                0 non-null      float64
 57  Security Staff                   0 non-null      float64
 58  Other Facilities                 0 non-null      float64
dtypes: float64(48), object(11)
memory usage: 8.2+ MB

In [8]:
# Total number of rows in dataset
len(df)

18255

In [9]:
# Identify missing values using
df.isnull().sum()

Title                                 16
URL                                    0
City                                   0
Type                                  16
Area                                  16
Price                                 16
Purpose                               16
Location                              16
Description                         3362
Built in year                       6315
Parking Spaces                      8599
Double Glazed Windows              18255
Central Air Conditioning           18255
Central Heating                    18255
Flooring                           18255
Electricity Backup                 18255
Waste Disposal                     18255
Floors                              9889
Other Main Features                18255
Furnished                          18255
Bedrooms                              16
Bathrooms                             16
Servant Quarters                    8598
Drawing Room                       18255
Dining Room                        18255
Kitchens                            4999
Study Room                         18255
Prayer Room                        18255
Powder Room                        18255
Store Rooms                         8536
Steam Room                         18255
Lounge or Sitting Room             18255
Laundry Room                       18255
Other Rooms                        18255
Broadband Internet Access          18255
Satellite or Cable TV Ready        18255
Intercom                           18255
Community Lawn or Garden           18255
Community Swimming Pool            18255
Community Gym                      18255
First Aid or Medical Centre        18255
Day Care Centre                    18255
Kids Play Area                     18255
Barbeque Area                      18255
Mosque                             18255
Community Centre                   18255
Lawn or Garden                     18255
Sauna                              18255
Jacuzzi                            18255
Nearby Schools                     18255
Nearby Hospitals                   18255
Nearby Shopping Malls              18255
Nearby Restaurants                 18255
Distance From Airport (kms)        18255
Nearby Public Transport Service    18255
Other Nearby Places                18255
Maintenance Staff                  18255
Security Staff                     18255
Other Facilities                   18255
dtype: int64

In [10]:
print(f"Original shape")

rows, columns = df.shape
print(f"\nDataset contains {rows} rows and {columns} columns.")

Original shape

Dataset contains 18255 rows and 59 columns.

In [11]:
df.columns = df.columns.str.strip()

In [12]:
print(f"All column names before cleaning\n")
df.columns

All column names before cleaning

Index(['Title', 'URL', 'City', 'Type', 'Area', 'Price', 'Purpose', 'Location',
       'Description', 'Built in year', 'Parking Spaces',
       'Double Glazed Windows', 'Central Air Conditioning', 'Central Heating',
       'Flooring', 'Electricity Backup', 'Waste Disposal', 'Floors',
       'Other Main Features', 'Furnished', 'Bedrooms', 'Bathrooms',
       'Servant Quarters', 'Drawing Room', 'Dining Room', 'Kitchens',
       'Study Room', 'Prayer Room', 'Powder Room', 'Store Rooms', 'Steam Room',
       'Lounge or Sitting Room', 'Laundry Room', 'Other Rooms',
       'Broadband Internet Access', 'Satellite or Cable TV Ready', 'Intercom',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre', 'Lawn or Garden',
       'Sauna', 'Jacuzzi', 'Nearby Schools', 'Nearby Hospitals',
       'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Other Facilities'],
      dtype='object')

In [13]:
# Drop columns where all values are NaN
df.dropna(axis=1, how='all', inplace=True)

# Unpack shape into row and column count
rows, columns = df.shape

# Print with labels
print(f"Cleaned DataFrame shape : {rows} rows × {columns} columns")

Cleaned DataFrame shape : 18255 rows × 17 columns

In [14]:
# View All Column Names
print(f"Column names after cleaning\n")
df.columns

Column names after cleaning

Index(['Title', 'URL', 'City', 'Type', 'Area', 'Price', 'Purpose', 'Location',
       'Description', 'Built in year', 'Parking Spaces', 'Floors', 'Bedrooms',
       'Bathrooms', 'Servant Quarters', 'Kitchens', 'Store Rooms'],
      dtype='object')

In [17]:
# statistical description of datafram
df.describe()

,Built in year,Parking Spaces,Floors,Servant Quarters,Kitchens,Store Rooms
count,11940.000000,9656.000000,8366.000000,9657.000000,13256.000000,9719.000000
mean,1967.123744,5.251833,2.393677,1.236823,1.686859,1.169565
std,1949.941225,41.917894,22.849369,0.706476,2.022453,0.495977
min,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,2020.000000,1.000000,2.000000,1.000000,1.000000,1.000000
50%,2024.000000,2.000000,2.000000,1.000000,2.000000,1.000000
75%,2025.000000,3.000000,2.000000,1.000000,2.000000,1.000000
max,202122.000000,2015.000000,2018.000000,22.000000,211.000000,18.000000

In [18]:
# Check for total number of duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows Detected: {duplicate_count}")

# View sample duplicate entries (if any)
if duplicate_count > 0:
    print("Sample Duplicate Rows:")
    display(df[df.duplicated()].head())

# Remove duplicate rows permanently
df.drop_duplicates(inplace=True)

# Confirm removal
print(f"\nDuplicates Removed. New shape: {df.shape}")

Duplicate Rows Detected: 0

Duplicates Removed. New shape: (18255, 17)

In [19]:
# Check for duplicates based on these columns
df.duplicated(subset=['Title', 'Area', 'Price']).sum()

np.int64(559)

In [20]:
# Drop duplicates based on key listing attributes
df.drop_duplicates(subset=['Title', 'Area', 'Price'], inplace=True)

In [21]:
# Count total duplicate rows (all columns)
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows (all columns): {duplicate_count}")

Total duplicate rows (all columns): 0

In [21]:
print("Price Unique Values :", df['Price'].nunique()) # count of distinct values
print("Price Duplicates.   :", df['Price'].duplicated().sum())

print("\nArea Unique Values:", df['Area'].nunique()) # # count of distinct values
print("Area Duplicates:    :", df['Area'].duplicated().sum())

Price Unique Values : 1022
Price Duplicates.   : 16673

Area Unique Values: 468
Area Duplicates:    : 17227

In [22]:
# View messy columns
print("\nTop 10 Price Values:\n", df['Price'].value_counts().head(10))
print("\n\nTop 10 Area Values:\n", df['Area'].value_counts().head(10))

Top 10 Price Values:
 Price
PKR\n60 Thousand    261
PKR\n45 Thousand    226
PKR\n50 Thousand    221
PKR\n70 Thousand    211
PKR\n3.5 Crore      208
PKR\n80 Thousand    204
PKR\n65 Thousand    203
PKR\n2.5 Crore      201
PKR\n55 Thousand    198
PKR\n90 Thousand    196
Name: count, dtype: int64


Top 10 Area Values:
 Area
5 Marla        3355
10 Marla       2889
1 Kanal        2047
7 Marla         847
6 Marla         445
4 Marla         412
8 Marla         354
500 Sq. Yd.     349
3 Marla         330
12 Marla        321
Name: count, dtype: int64

In [23]:
# Clean messy columns ( e.g., remove commas, PKR symbols)
import numpy as np

def clean_price_column(series):
    cleaned = (
        series.astype(str)
              .str.replace(',', '', regex=False)
              .str.replace('PKR', '', regex=False)
              .str.replace('Rs.', '', regex=False)
              .str.strip()
              .str.lower()
    )

    # Convert Lakh and Crore to numbers
    def convert_units(value):
        try:
            if 'crore' in value:
                num = float(value.replace('crore', '').strip())
                return num * 1e7
            elif 'lakh' in value:
                num = float(value.replace('lakh', '').strip())
                return num * 1e5
            else:
                return float(value)
        except:
            return np.nan

    return cleaned.apply(convert_units)

In [24]:
# View Price
df['Price'] = clean_price_column(df['Price'])

# Preview result
print(df[['Price']].head())

        Price
0  47500000.0
1  62500000.0
2  34500000.0
3  29800000.0
4  46500000.0

In [25]:
# Convert area units (marla/kanal/sqft → uniform sqft), if required

def clean_area_column(series):
    unit_map = {
        'marla': 272.25,
        'kanal': 5445,
        'sq yards': 9,
        'sq. yards': 9,
        'sq meter': 10.7639,
        'sq. meter': 10.7639,
        'square meter': 10.7639,
        'sq ft': 1,
        'sq. ft': 1,
        'square feet': 1
    }

    cleaned = (
        series.astype(str)
              .str.replace(',', '', regex=False)
              .str.lower()
              .str.strip()
    )

    def convert_area(value):
        for unit in unit_map:
            if unit in value:
                try:
                    num = float(value.replace(unit, '').strip())
                    return num * unit_map[unit]
                except:
                    return np.nan
        try:
            return float(value)  # If it's already in sqft
        except:
            return np.nan

    return cleaned.apply(convert_area)

In [26]:
# View Area
df['Area'] = clean_area_column(df['Area'])
df['Area'].dropna().head(10).tolist()

[1932.975,
 816.75,
 2178.0,
 2722.5,
 2722.5,
 2178.0,
 2722.5,
 1932.975,
 2994.75,
 5445.0]

In [ ]:
# # Categorical Column Analysis
# print("\n\n. Categorical Column Analysis")

# for col in df.columns:

#     # Print column header
#     print(f"\nAnalysis for column: ' {col} ' ")

#     # Show unique values (categories present in the column)
#     print("\nUnique values:", df[col].unique())

#     # Show frequency count of each category
#     print("\nUnique Value counts:", df[col].value_counts())

#     print("---------------------------------------------")

In [27]:
# Integer count of distinct values
print("\nInteger count of distinct values:\n")
for column in df:

    # Show unique values
    print(column,df[column].nunique())

Integer count of distinct values:

Title 16064
URL 17696
City 83
Type 7
Area 216
Price 904
Purpose 2
Location 1048
Description 13437
Built in year 95
Parking Spaces 46
Floors 20
Bedrooms 23
Bathrooms 17
Servant Quarters 14
Kitchens 10
Store Rooms 10

#### **Section 3. Missing Values Treatment**

In [28]:
# Section 3. Missing Values Treatment

# Identify Missing Values

# Missing Values - Function
import pandas as pd

def check_missing_values(df):
    """
    Returns a DataFrame summarizing missing values in the input DataFrame.

    Columns:
    - 'Missing Values': total number of missing values in each column
    - 'Percentage (%)': percentage of missing values in each column
    """
    # 1. Total missing values in each column
    missing_counts = df.isnull().sum()

    # 2. Percentage of missing values
    missing_percent = (missing_counts / len(df)) * 100

    # 3. Combine into a single DataFrame
    missing_summary = pd.DataFrame({
        'Missing Values': missing_counts,
        'Percentage (%)': missing_percent.round(2)
    })

    # 4. Filter only columns with missing values
    missing_summary = missing_summary[missing_summary['Missing Values'] > 0]

    return missing_summary

# calling function
print("\nSummary of Missing Values:")

missing_info = check_missing_values(df)
print(missing_info)

Summary of Missing Values:
                  Missing Values  Percentage (%)
Title                          1            0.01
Type                           1            0.01
Area                        2803           15.84
Price                       3480           19.67
Purpose                        1            0.01
Location                       1            0.01
Description                 3255           18.39
Built in year               6081           34.36
Parking Spaces              8266           46.71
Floors                      9593           54.21
Bedrooms                       1            0.01
Bathrooms                      1            0.01
Servant Quarters            8313           46.98
Kitchens                    4818           27.23
Store Rooms                 8223           46.47

### **Strategies for Missing Data**

| Missing Data Level         | Recommended Action                                                                 |
|----------------------------|-------------------------------------------------------------------------------------|
| **< 5% (Few)**             | Safe to delete or use simple imputation (mean/mode).                               |
| **5–30% (Moderate)**       | Prefer imputation. Choose method carefully to avoid distorting variance/correlation. |
| **> 30% (High)**           | Avoid deletion. Use advanced imputation or drop column if mostly missing.          |


#### **Many missing values (>30%) :**

**Avoid listwise deletion.** Drop the column only if it's mostly missing and not essential. Impute using advanced methods if the feature is important — avoid simple imputation to prevent data distortion.

In [29]:
# Drops all columns with > 40% missing data

# Define threshold: keep columns with at least 60% non-null values
threshold = len(df) * 0.6  # 60% of total rows

# Step 1: Find columns that don't meet the threshold
low_data_cols = [col for col in df.columns if df[col].count() < threshold]

# Step 2: Drop those columns from the DataFrame
df.drop(columns=low_data_cols, inplace=True)

# Step 3: Print final shape and results
rows, cols = df.shape
print(f"\nCleaned DataFrame shape: {rows} rows × {cols} columns")

print("\nRemaining columns in the DataFrame:")
print(df.columns.tolist())

print("\nDropped columns (with < 60% non-null values):")
print(low_data_cols)

Cleaned DataFrame shape: 17696 rows × 13 columns

Remaining columns in the DataFrame:
['Title', 'URL', 'City', 'Type', 'Area', 'Price', 'Purpose', 'Location', 'Description', 'Built in year', 'Bedrooms', 'Bathrooms', 'Kitchens']

Dropped columns (with < 60% non-null values):
['Parking Spaces', 'Floors', 'Servant Quarters', 'Store Rooms']

In [30]:
print("\nSummary of Missing Values: Dropped all columns with more than 40% missing data\n")

missing_info = check_missing_values(df)
print(missing_info)

Summary of Missing Values: Dropped all columns with more than 40% missing data

               Missing Values  Percentage (%)
Title                       1            0.01
Type                        1            0.01
Area                     2803           15.84
Price                    3480           19.67
Purpose                     1            0.01
Location                    1            0.01
Description              3255           18.39
Built in year            6081           34.36
Bedrooms                    1            0.01
Bathrooms                   1            0.01
Kitchens                 4818           27.23

In [31]:
## Mode Imputation (Categorical or Repetitive Numerical)
# Mode is best when data has frequent repeating values.

# Mode Imputation : Replace missing values in a column with the mode (the most frequent value) of the observed values.
# Applicable to both numerical and categorical data. Simple


df['Type'] = df['Type'].fillna(df['Type'].mode()[0])         # Property type is categorical
df['Purpose'] = df['Purpose'].fillna(df['Purpose'].mode()[0]) # Purpose (e.g. Rent, Buy)
df['Area'] = df['Area'].fillna(df['Area'].mode()[0])         # Repetitive numeric values

In [32]:
# Mode Values
print("Mode Type:", df['Type'].mode()[0])
print("Mode Purpose:", df['Purpose'].mode()[0])
print("Mode Area:", df['Area'].mode()[0])

Mode Type: House
Mode Purpose: For Sale
Mode Area: 1361.25

In [33]:
## Forward Fill (Temporal or Grouped Context)
# Forward fill is useful when missing data likely follows a pattern from previous rows.

df['Location'] = df['Location'].ffill()  # Use .ffill() to avoid deprecation warnings
df['Title'] = df['Title'].ffill()

In [34]:
## Mean Imputation (Numerical & Fairly Symmetric)
# Mean replaces missing values with the average.

# Mean Imputation : Replace missing values in a numerical column with the mean
# Convert all values to numbers

df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Built in year'] = pd.to_numeric(df['Built in year'], errors='coerce')
df['Bedrooms'] = pd.to_numeric(df['Bedrooms'], errors='coerce')
df['Bathrooms'] = pd.to_numeric(df['Bathrooms'], errors='coerce')
df['Kitchens'] = pd.to_numeric(df['Kitchens'], errors='coerce')

df['Price'] = df['Price'].fillna(df['Price'].mean())
df['Built in year'] = df['Built in year'].fillna(df['Built in year'].mean())
df['Bedrooms'] = df['Bedrooms'].fillna(df['Bedrooms'].mean())
df['Bathrooms'] = df['Bathrooms'].fillna(df['Bathrooms'].mean())
df['Kitchens'] = df['Kitchens'].fillna(df['Kitchens'].mean())

In [36]:
## Mean Values
print("Mean Price:", df['Price'].mean())
print("Mean Bedrooms:", df['Bedrooms'].mean())

Mean Price: 36945247.819358476
Mean Bedrooms: 4.1630241121273315

In [35]:
# Handle Description: create binary flag for presence of text
df['Has_Description'] = df['Description'].notnull().astype(int)

**Justification**:

**Mode Imputation (Categorical or Repetitive Numerical)**

**Type, Purpose, Area**

- These columns are categorical or contain frequently repeated values.

- Mode fills in the most common value, preserving dominant patterns.

- Area might be numeric, but if highly repeated (e.g. common plot sizes), mode is appropriate.

**Forward Fill (Temporal or Grouped Context)**

**Location, Title**

- Data like location and title often follow a grouped or ordered pattern.

- Forward-fill carries context from adjacent rows—ideal for structured or sequential listings.

- Updated to ffill() to avoid deprecation warnings with method='ffill'.

**Mean Imputation (Numerical & Fairly Symmetric)**

**Price, Badrooms, Bethrooms, Kitchens**

- These columns are purely numerical and missing rates are manageable.

- If distributions are not heavily skewed, mean maintains smooth continuity.

- Works well when data is relatively symmetric and consistent.

**Create a Binary Flag for Text**

**Description**

- Checks whether the Description column is not null (notnull()).

- Converts the resulting Boolean (True / False) to an integer (1 / 0).

- Adds a new column called Has_Description with:

 - 1 → if there's text present

 - 0 → if the field is empty or NaN

In [36]:
#  Show If 'posting_date' Was Processed : To confirm if the column exists and was filled:
if 'posting_date' in df.columns:
    print(df['posting_date'].isnull().sum())
    print(df['posting_date'].head())
else:
    print("No 'posting_date' column found.")

# Only do this if 'posting_date' exists
if 'posting_date' in df.columns:
    df['posting_date'] = df['posting_date'].fillna(method='ffill')

No 'posting_date' column found.

#### **Section 4. Data Cleaning & Consistency**

In [40]:
# get all the values in the 'City' column

#df['City']=df['City'].str.lower()

cities = df['City'].unique()

# print(cities)

# sort them alphabetically and then take a closer look
cities.sort()
cities

array(['Abbottabad', 'Abbottabad ', 'Attock', 'Attock ', 'Bahawalpur',
       'Bahawalpur ', 'Buner', 'Burewala', 'Chakwal', 'Chilas', 'Chiniot',
       'Daska', 'Dera Ghazi Khan', 'Dera Ghazi Khan ', 'Dera Ismail Khan',
       'Faisalabad', 'Faisalabad ', 'Fateh Jang', 'Galyat', 'Gharo',
       'Gujar Khan', 'Gujranwala', 'Gujranwala ', 'Gujrat', 'Gujrat ',
       'Gwadar', 'Hafizabad', 'Haripur', 'Hyderabad', 'Hyderabad ',
       'Islamabad', 'Islamabad ', 'Jamshoro', 'Jhang', 'Jhelum',
       'Jhelum ', 'Karachi', 'Karachi ', 'Kasur', 'Kharian', 'Lahore',
       'Lahore ', 'Lalamusa', 'Lodhran', 'Mardan', 'Mardan ', 'Mirpur',
       'Mirpur Khas', 'Multan', 'Multan ', 'Murree', 'Murree ',
       'Nowshera', 'Nowshera ', 'Okara', 'Okara ', 'Pakpattan',
       'Peshawar', 'Peshawar ', 'Quetta', 'Rahim Yar Khan',
       'Rahim Yar Khan ', 'Rawalpindi', 'Rawalpindi ', 'Sadiqabad',
       'Sahiwal', 'Sahiwal ', 'Sarai Alamgir', 'Sarai Alamgir ',
       'Sargodha', 'Sargodha ', 'Sheikhupura', 'Sheikhupura ', 'Sialkot',
       'Sialkot  ', 'Sukkur', 'Swat', 'Talagang', 'Taxila', 'Taxila ',
       'Vehari', 'Wah', 'Wah '], dtype=object)

In [41]:

# # Remove extra spaces : Strip whitespace from columns
df['City'] = df['City'].str.strip()

In [42]:
# get the top 10 closest matches to "south korea"
matches = fuzzywuzzy.process.extract("abbottabad", cities, limit=5)

# take a look at them
matches

[('Abbottabad', 100),
 ('Abbottabad ', 100),
 ('Hafizabad', 53),
 ('Islamabad', 53),
 ('Islamabad ', 53)]

In [43]:
# Section 4. Data Cleaning & Consistency : FuzzyWuzzy

# FuzzyWuzzy

# function to replace rows in the provided column of the provided dataframe
# that match the provided string above the provided ratio with the provided string
def replace_matches_in_column(df, column, string_to_match, min_match = 95):
    # get a list of unique strings
    strings = df[column].unique()

    # get the top 10 closest matches to our input string
    matches = fuzzywuzzy.process.extract(string_to_match, strings,
                                         limit=5)

    # only get matches with a ratio > 95
    close_matches = [matches[0] for matches in matches if matches[1] >= min_match]

    # get the rows of all the close matches in our dataframe
    rows_with_matches = df[column].isin(close_matches)

    # replace all rows with close matches with the input matches
    df.loc[rows_with_matches, column] = string_to_match

    # let us know the function's done
    #print("All done!")

    print(f"Standardized to '{string_to_match}': {close_matches}\n")
    return df

**Detect and Correct Inconsistent City Name**

City names often suffer from inconsistent spelling or whitespace issues. Fuzzy matching helps normalize entries with high similarity scores (e.g., "Lahore", "Lahor")

In [44]:
replace_matches_in_column(df=df, column='City', string_to_match="Islamabad",min_match = 97)
df.City.unique()

Standardized to 'Islamabad': ['Islamabad']

array(['Karachi', 'Islamabad', 'Faisalabad', 'Multan', 'Rawalpindi',
       'Peshawar', 'Jhelum', 'Murree', 'Hyderabad', 'Bahawalpur',
       'Sialkot', 'Abbottabad', 'Sahiwal', 'Lahore', 'Gujrat', 'Wah',
       'Sargodha', 'Sheikhupura', 'Chakwal', 'Nowshera', 'Mardan',
       'Chilas', 'Sarai Alamgir', 'Quetta', 'Rahim Yar Khan', 'Okara',
       'Attock', 'Dera Ghazi Khan', 'Taxila', 'Sukkur', 'Gwadar', 'Kasur',
       'Mirpur', 'Haripur', 'Gujar Khan', 'Gharo', 'Mirpur Khas', 'Swat',
       'Daska', 'Sadiqabad', 'Buner', 'Jhang', 'Lalamusa', 'Lodhran',
       'Pakpattan', 'Chiniot', 'Dera Ismail Khan', 'Fateh Jang',
       'Burewala', 'Hafizabad', 'Talagang', 'Vehari', 'Jamshoro',
       'Galyat', 'Gujranwala', 'Kharian'], dtype=object)

**Detect and Correct Inconsistent Property Types**

“Type” should represent a clean categorical field. Variations caused by case sensitivity or typos are fixed by grouping similar strings using fuzzy logic.

In [45]:
#View Unique Values

df['Type'] = df['Type'].astype(str).str.strip().str.lower()  # clean whitespace
df['Type'].value_counts()

Type
house            12929
flat              2848
upper portion     1213
lower portion      554
farm house          87
room                43
penthouse           22
Name: count, dtype: int64

In [46]:
# Combine Similar Types : group upper portion and lower portion as just "portion"
df['Type'] = df['Type'].replace({'upper portion': 'portion', 'lower portion': 'portion'})

In [47]:
# Unique values in categorical columns
print("\nUnique values in categorical columns:")
for col in ['Type']:  # Example categorical columns
    print(f"\nColumn '{col}':")
    print("\nCount Distinct (Unique) Values :",df[col].nunique())
    print("\nNumber of Unique Values :",df[col].unique())
    print("\nCount of Each Unique Value in a Column :",df[col].value_counts())

Unique values in categorical columns:

Column 'Type':

Count Distinct (Unique) Values : 6

Number of Unique Values : ['flat' 'house' 'portion' 'penthouse' 'farm house' 'room']

Count of Each Unique Value in a Column : Type
house         12929
flat           2848
portion        1767
farm house       87
room             43
penthouse        22
Name: count, dtype: int64

In [48]:
df = replace_matches_in_column(df, column='Type', string_to_match='House', min_match=90)
df = replace_matches_in_column(df, column='Type', string_to_match='Flat', min_match=90)
df = replace_matches_in_column(df, column='Type', string_to_match='Portion', min_match=90)

Standardized to 'House': ['house', 'penthouse', 'farm house']

Standardized to 'Flat': ['flat']

Standardized to 'Portion': ['portion']

In [46]:
# for col in df.columns:  # Example categorical columns
#     print(f"\nColumn '{col}':")
#     print("\nNumber of Unique Values, nunique() :",df[col].nunique())
#     print("value_counts :",df[col].value_counts())
#     print("---------------------------------------------\n")

**Remove Outliers Using IQR Method**

**Detect outliers for numeric columns Price**

**Justification:**  Outliers can distort modeling and statistical summaries. IQR method is robust to non-normal distributions and helps clean extreme values for features like price

In [49]:
# Function to Remove Outliers Using IQR for a Given Column

def remove_outliers_iqr(data, column):
    # Calculate the first quartile (25th percentile)
    Q1 = data[column].quantile(0.25)

    # Calculate the third quartile (75th percentile)
    Q3 = data[column].quantile(0.75)

    # Calculate the interquartile range (middle 50% spread)
    IQR = Q3 - Q1

    # Determine lower and upper bounds for outliers
    lower_bound = Q1 - 1.5 * IQR  # Threshold for low-end outliers
    upper_bound = Q3 + 1.5 * IQR  # Threshold for high-end outliers

    # Print bounds for diagnostic reference
    print(f"{column} - Lower Bound: {lower_bound}, Upper Bound: {upper_bound}\n")

    # Filter the DataFrame to include only values within bounds
    filtered_df = data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

    # Return the cleaned DataFrame
    return filtered_df

In [50]:
df_clean = remove_outliers_iqr(df, 'Price')  # Removes price outliers
df_clean = remove_outliers_iqr(df_clean, 'Built in year')  # Optional: chain for another column

# Check new shape of dataset
print("Dataset shape after IQR outlier removal:", df_clean.shape)

Price - Lower Bound: -29167871.729037702, Upper Bound: 76613119.54839617

Built in year - Lower Bound: 1882.951894102454, Upper Bound: 2108.6288635385276

Dataset shape after IQR outlier removal: (15770, 14)

#### **Section 5: Feature Engineering**

In [51]:
# Section 5: Feature Engineering

# Price per Square Foot (or Marla)

# Standardize area unit first if needed (assume already in square feet)
# Calculate price per square foot
df['Price_per_sqft'] = df['Price'] / df['Area']

In [53]:
# Property Age

from datetime import datetime

# Get current year
current_year = datetime.now().year

df['Built in year'] = pd.to_numeric(df['Built in year'], errors='coerce')

# Calculate estimated property age
df['property_age'] = current_year - df['Built in year']

In [54]:
# Binary Flag for Description

df['has_description'] = df['Description'].notnull().astype(int)

In [56]:
# Total Rooms (Bedrooms + Bathrooms + Kitchens)

df['total_rooms'] = df['Bedrooms'] + df['Bathrooms'] + df['Kitchens']

In [ ]:
# Is Popular Location

# Flag listings from the most frequent location
popular_location = df['Location'].mode()[0]
df['is_popular_location'] = (df['Location'] == popular_location).astype(int)

#### **Feature Engineering: Creating New Informative Columns**

**Price Per Square Foot**

**`df['price_per_sqft'] = df['Price'] / df['Area']`**

- Gives a normalized price metric, helping compare listings across different sizes. Useful for detecting overpriced properties and regional pricing variations.
- Normalizes price across listings of different sizes
- **Use case**: Flag overpriced/underpriced properties, regional price comparisons

**Property Age**

**`df['property_age'] = current_year - df['Built in year']`**

- Highlights how old the listing is, newer ones might be more relevant or realistic. Can also be used to filter stale entries or prioritize fresh data.
- Older properties may require renovation, affecting value  
- **Use case**: Analyze price trends by age, categorize legacy vs new builds


**Binary Flag for Description**

**`df['has_description'] = df['Description'].notnull().astype(int)`**  

- Flags whether a listing has text info. Often correlates with data quality or user engagement. Can be useful for modeling and filtering incomplete entries.
- Textual descriptions often boost listing quality  
- **Use case**: Feature for modeling user engagement or quality filtering  


**Total Rooms (Bedrooms + Bathrooms + Kitchens)**

**`df['total_rooms'] = df['Bedrooms'] + df['Bathrooms'] + df['Kitchens']`**  

- Gives a quick sense of overall property scale. Useful for clustering and scoring listings.
- Gives a simple scale for property size  
- **Use case**: Clustering properties, scoring livable space  

**Is Popular Location**

**`popular_location = df['Location'].mode()[0]`**

**`df['is_popular_location'] = (df['Location'] == popular_location).astype(int)`**  

- Spotlights listings from high-demand areas. This feature could carry predictive weight in pricing or ranking models.
- Highlights listings from high-demand neighborhoods
- **Use case:** Can serve as proxy for pricing power or desirability