<a href="https://colab.research.google.com/github/raheelam98/DataAnalysis/blob/main/EDA_Projects/Zameen_EDA_Project/NoteBook/Zameen_EDA_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Zameen.com**

In [ ]:
#Mount Google Drive in Colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#List Files in a Folder
!ls /content/drive/MyDrive/EDA/

ai_adoption_dataset.csv  pakistan_intellectual_capital.csv
bus_fare_dataset.csv	 Scarped_Zameen.xlsx

In [ ]:
import pandas as pd

# Correct path and filename
df = pd.read_excel('/content/drive/MyDrive/EDA/Scarped_Zameen.xlsx')

In [ ]:
df.head()

,Title,URL,City,Type,Area,Price,Purpose,Location,Description,Built in year,...,Nearby Schools,Nearby Hospitals,Nearby Shopping Malls,Nearby Restaurants,Distance From Airport (kms),Nearby Public Transport Service,Other Nearby Places,Maintenance Staff,Security Staff,Other Facilities
0,Hmr Waterfront 2 Bed Room Premium Apartment On...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,128 Sq. Yd.,PKR\n4.75 Crore,For Sale,"DHA Defence, Karachi, Sindh",SAIMA MARINA RESIDENCE HMR WATERFRONT\nINVESTO...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chance Deal! Luxury 2 Bedroom Seafront Apartme...,https://www.zameen.com/Property/dha_defence_dh...,Karachi,Flat,161 Sq. Yd.,PKR\n6.25 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n2 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Luxury 1 Bed At H& S Residence By Japanese Arc...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,111 Sq. Yd.,PKR\n3.45 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n1 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Luxury 1 Bed Seafront Apartment at HMR waterfr...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,106 Sq. Yd.,PKR\n2.98 Crore,For Sale,"DHA Defence, Karachi, Sindh",Chance Deal at HMR Waterfront 1-Bed Apartment ...,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2 Bed Apartment For Booking On 3 Years | Saima...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,156 Sq. Yd.,PKR\n4.65 Crore,For Sale,"DHA Defence, Karachi, Sindh",HMR WATERFRONT \n\nOwn Your Dream Apartment in...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Check Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18255 entries, 0 to 18254
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Title                            18239 non-null  object
 1   URL                              18255 non-null  object
 2   City                             18255 non-null  object
 3   Type                             18239 non-null  object
 4   Area                             18239 non-null  object
 5   Price                            18239 non-null  object
 6   Purpose                          18239 non-null  object
 7   Location                         18239 non-null  object
 8   Description                      14893 non-null  object
 9   Built in year                    11940 non-null  float64
 10  Parking Spaces                   9656 non-null   float64
 11  Double Glazed Windows            0 non-null      float64
 12  Central Air Conditioning         0 non-null      float64
 13  Central Heating                  0 non-null      float64
 14  Flooring                         0 non-null      float64
 15  Electricity Backup               0 non-null      float64
 16  Waste Disposal                   0 non-null      float64
 17  Floors                           8366 non-null   float64
 18  Other Main Features              0 non-null      float64
 19  Furnished                        0 non-null      float64
 20  Bedrooms                         18239 non-null  object
 21  Bathrooms                        18239 non-null  object
 22  Servant Quarters                 9657 non-null   float64
 23  Drawing Room                     0 non-null      float64
 24  Dining Room                      0 non-null      float64
 25  Kitchens                         13256 non-null  float64
 26  Study Room                       0 non-null      float64
 27  Prayer Room                      0 non-null      float64
 28  Powder Room                      0 non-null      float64
 29  Store Rooms                      9719 non-null   float64
 30  Steam Room                       0 non-null      float64
 31  Lounge or Sitting Room           0 non-null      float64
 32  Laundry Room                     0 non-null      float64
 33  Other Rooms                      0 non-null      float64
 34  Broadband Internet Access        0 non-null      float64
 35  Satellite or Cable TV Ready      0 non-null      float64
 36  Intercom                         0 non-null      float64
 37  Community Lawn or Garden         0 non-null      float64
 38  Community Swimming Pool          0 non-null      float64
 39  Community Gym                    0 non-null      float64
 40  First Aid or Medical Centre      0 non-null      float64
 41  Day Care Centre                  0 non-null      float64
 42  Kids Play Area                   0 non-null      float64
 43  Barbeque Area                    0 non-null      float64
 44  Mosque                           0 non-null      float64
 45  Community Centre                 0 non-null      float64
 46  Lawn or Garden                   0 non-null      float64
 47  Sauna                            0 non-null      float64
 48  Jacuzzi                          0 non-null      float64
 49  Nearby Schools                   0 non-null      float64
 50  Nearby Hospitals                 0 non-null      float64
 51  Nearby Shopping Malls            0 non-null      float64
 52  Nearby Restaurants               0 non-null      float64
 53  Distance From Airport (kms)      0 non-null      float64
 54  Nearby Public Transport Service  0 non-null      float64
 55  Other Nearby Places              0 non-null      float64
 56  Maintenance Staff                0 non-null      float64
 57  Security Staff                   0 non-null      float64
 58  Other Facilities                 0 non-null      float64
dtypes: float64(48), object(11)
memory usage: 8.2+ MB

In [ ]:
# statistical description of datafram
df.describe()

,Built in year,Parking Spaces,Double Glazed Windows,Central Air Conditioning,Central Heating,Flooring,Electricity Backup,Waste Disposal,Floors,Other Main Features,...,Nearby Schools,Nearby Hospitals,Nearby Shopping Malls,Nearby Restaurants,Distance From Airport (kms),Nearby Public Transport Service,Other Nearby Places,Maintenance Staff,Security Staff,Other Facilities
count,11940.000000,9656.000000,0.0,0.0,0.0,0.0,0.0,0.0,8366.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1967.123744,5.251833,NaN,NaN,NaN,NaN,NaN,NaN,2.393677,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1949.941225,41.917894,NaN,NaN,NaN,NaN,NaN,NaN,22.849369,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2020.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2024.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2025.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,202122.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# total number of rows
len(df)

18255

In [ ]:
# Check for missing values
df.isnull().sum()

Title                                 16
URL                                    0
City                                   0
Type                                  16
Area                                  16
Price                                 16
Purpose                               16
Location                              16
Description                         3362
Built in year                       6315
Parking Spaces                      8599
Double Glazed Windows              18255
Central Air Conditioning           18255
Central Heating                    18255
Flooring                           18255
Electricity Backup                 18255
Waste Disposal                     18255
Floors                              9889
Other Main Features                18255
Furnished                          18255
Bedrooms                              16
Bathrooms                             16
Servant Quarters                    8598
Drawing Room                       18255
Dining Room                        18255
Kitchens                            4999
Study Room                         18255
Prayer Room                        18255
Powder Room                        18255
Store Rooms                         8536
Steam Room                         18255
Lounge or Sitting Room             18255
Laundry Room                       18255
Other Rooms                        18255
Broadband Internet Access          18255
Satellite or Cable TV Ready        18255
Intercom                           18255
Community Lawn or Garden           18255
Community Swimming Pool            18255
Community Gym                      18255
First Aid or Medical Centre        18255
Day Care Centre                    18255
Kids Play Area                     18255
Barbeque Area                      18255
Mosque                             18255
Community Centre                   18255
Lawn or Garden                     18255
Sauna                              18255
Jacuzzi                            18255
Nearby Schools                     18255
Nearby Hospitals                   18255
Nearby Shopping Malls              18255
Nearby Restaurants                 18255
Distance From Airport (kms)        18255
Nearby Public Transport Service    18255
Other Nearby Places                18255
Maintenance Staff                  18255
Security Staff                     18255
Other Facilities                   18255
dtype: int64

In [ ]:
# Dropping Columns / Rows in Pandas (Permanent Change)
# df.drop('column_name', axis=1, inplace=True)

df.drop(['Double Glazed Windows', 'col2', 'col3'], axis=1, inplace=True)

In [ ]:
# Missing Values - Function
import pandas as pd

def check_missing_values(df):
    """
    Returns a DataFrame summarizing missing values in the input DataFrame.

    Columns:
    - 'Missing Values': total number of missing values in each column
    - 'Percentage (%)': percentage of missing values in each column
    """
    # 1. Total missing values in each column
    missing_counts = df.isnull().sum()

    # 2. Percentage of missing values
    missing_percent = (missing_counts / len(df)) * 100

    # 3. Combine into a single DataFrame
    missing_summary = pd.DataFrame({
        'Missing Values': missing_counts,
        'Percentage (%)': missing_percent.round(2)
    })

    # 4. Filter only columns with missing values
    missing_summary = missing_summary[missing_summary['Missing Values'] > 0]

    return missing_summary

 # calling function
print("\n\nSummary of Missing Values:")

missing_info = check_missing_values(df)
print(missing_info)

Summary of Missing Values:
                                 Missing Values  Percentage (%)
Title                                        16            0.09
Type                                         16            0.09
Area                                         16            0.09
Price                                        16            0.09
Purpose                                      16            0.09
Location                                     16            0.09
Description                                3362           18.42
Built in year                              6315           34.59
Parking Spaces                             8599           47.10
Double Glazed Windows                     18255          100.00
Central Air Conditioning                  18255          100.00
Central Heating                           18255          100.00
Flooring                                  18255          100.00
Electricity Backup                        18255          100.00
Waste Disposal                            18255          100.00
Floors                                     9889           54.17
Other Main Features                       18255          100.00
Furnished                                 18255          100.00
Bedrooms                                     16            0.09
Bathrooms                                    16            0.09
Servant Quarters                           8598           47.10
Drawing Room                              18255          100.00
Dining Room                               18255          100.00
Kitchens                                   4999           27.38
Study Room                                18255          100.00
Prayer Room                               18255          100.00
Powder Room                               18255          100.00
Store Rooms                                8536           46.76
Steam Room                                18255          100.00
Lounge or Sitting Room                    18255          100.00
Laundry Room                              18255          100.00
Other Rooms                               18255          100.00
Broadband Internet Access                 18255          100.00
Satellite or Cable TV Ready               18255          100.00
Intercom                                  18255          100.00
Community Lawn or Garden                  18255          100.00
Community Swimming Pool                   18255          100.00
Community Gym                             18255          100.00
First Aid or Medical Centre               18255          100.00
Day Care Centre                           18255          100.00
Kids Play Area                            18255          100.00
Barbeque Area                             18255          100.00
Mosque                                    18255          100.00
Community Centre                          18255          100.00
Lawn or Garden                            18255          100.00
Sauna                                     18255          100.00
Jacuzzi                                   18255          100.00
Nearby Schools                            18255          100.00
Nearby Hospitals                          18255          100.00
Nearby Shopping Malls                     18255          100.00
Nearby Restaurants                        18255          100.00
Distance From Airport (kms)               18255          100.00
Nearby Public Transport Service           18255          100.00
Other Nearby Places                       18255          100.00
Maintenance Staff                         18255          100.00
Security Staff                            18255          100.00
Other Facilities                          18255          100.00