<a href="https://colab.research.google.com/github/raheelam98/DataAnalysis/blob/main/EDA_Projects/Zameen_EDA_Project/NoteBook/Zameen_EDA_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Zameen.com**

In [ ]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [ ]:
#Mount Google Drive in Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#List Files in a Folder
!ls /content/drive/MyDrive/EDA/

ai_adoption_dataset.csv  pakistan_intellectual_capital.csv
bus_fare_dataset.csv	 Scarped_Zameen.xlsx

In [ ]:
import pandas as pd

# Correct path and filename
df = pd.read_excel('/content/drive/MyDrive/EDA/Scarped_Zameen.xlsx')

In [ ]:
# modules we'll use
# import pandas as pd
import numpy as np

# helpful modules
import fuzzywuzzy # pip install fuzzywuzzy
from fuzzywuzzy import process

/usr/local/lib/python3.11/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [ ]:
df.head()

,Title,URL,City,Type,Area,Price,Purpose,Location,Description,Built in year,...,Nearby Schools,Nearby Hospitals,Nearby Shopping Malls,Nearby Restaurants,Distance From Airport (kms),Nearby Public Transport Service,Other Nearby Places,Maintenance Staff,Security Staff,Other Facilities
0,Hmr Waterfront 2 Bed Room Premium Apartment On...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,128 Sq. Yd.,PKR\n4.75 Crore,For Sale,"DHA Defence, Karachi, Sindh",SAIMA MARINA RESIDENCE HMR WATERFRONT\nINVESTO...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chance Deal! Luxury 2 Bedroom Seafront Apartme...,https://www.zameen.com/Property/dha_defence_dh...,Karachi,Flat,161 Sq. Yd.,PKR\n6.25 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n2 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Luxury 1 Bed At H& S Residence By Japanese Arc...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,111 Sq. Yd.,PKR\n3.45 Crore,For Sale,"DHA Defence, Karachi, Sindh",Live the Seafront Dream at H&S Residence \n1 B...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Luxury 1 Bed Seafront Apartment at HMR waterfr...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,106 Sq. Yd.,PKR\n2.98 Crore,For Sale,"DHA Defence, Karachi, Sindh",Chance Deal at HMR Waterfront 1-Bed Apartment ...,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2 Bed Apartment For Booking On 3 Years | Saima...,https://www.zameen.com/Property/dha_phase_8_hm...,Karachi,Flat,156 Sq. Yd.,PKR\n4.65 Crore,For Sale,"DHA Defence, Karachi, Sindh",HMR WATERFRONT \n\nOwn Your Dream Apartment in...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 2-i) View basic info
# Check Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18255 entries, 0 to 18254
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Title                            18239 non-null  object
 1   URL                              18255 non-null  object
 2   City                             18255 non-null  object
 3   Type                             18239 non-null  object
 4   Area                             18239 non-null  object
 5   Price                            18239 non-null  object
 6   Purpose                          18239 non-null  object
 7   Location                         18239 non-null  object
 8   Description                      14893 non-null  object
 9   Built in year                    11940 non-null  float64
 10  Parking Spaces                   9656 non-null   float64
 11  Double Glazed Windows            0 non-null      float64
 12  Central Air Conditioning         0 non-null      float64
 13  Central Heating                  0 non-null      float64
 14  Flooring                         0 non-null      float64
 15  Electricity Backup               0 non-null      float64
 16  Waste Disposal                   0 non-null      float64
 17  Floors                           8366 non-null   float64
 18  Other Main Features              0 non-null      float64
 19  Furnished                        0 non-null      float64
 20  Bedrooms                         18239 non-null  object
 21  Bathrooms                        18239 non-null  object
 22  Servant Quarters                 9657 non-null   float64
 23  Drawing Room                     0 non-null      float64
 24  Dining Room                      0 non-null      float64
 25  Kitchens                         13256 non-null  float64
 26  Study Room                       0 non-null      float64
 27  Prayer Room                      0 non-null      float64
 28  Powder Room                      0 non-null      float64
 29  Store Rooms                      9719 non-null   float64
 30  Steam Room                       0 non-null      float64
 31  Lounge or Sitting Room           0 non-null      float64
 32  Laundry Room                     0 non-null      float64
 33  Other Rooms                      0 non-null      float64
 34  Broadband Internet Access        0 non-null      float64
 35  Satellite or Cable TV Ready      0 non-null      float64
 36  Intercom                         0 non-null      float64
 37  Community Lawn or Garden         0 non-null      float64
 38  Community Swimming Pool          0 non-null      float64
 39  Community Gym                    0 non-null      float64
 40  First Aid or Medical Centre      0 non-null      float64
 41  Day Care Centre                  0 non-null      float64
 42  Kids Play Area                   0 non-null      float64
 43  Barbeque Area                    0 non-null      float64
 44  Mosque                           0 non-null      float64
 45  Community Centre                 0 non-null      float64
 46  Lawn or Garden                   0 non-null      float64
 47  Sauna                            0 non-null      float64
 48  Jacuzzi                          0 non-null      float64
 49  Nearby Schools                   0 non-null      float64
 50  Nearby Hospitals                 0 non-null      float64
 51  Nearby Shopping Malls            0 non-null      float64
 52  Nearby Restaurants               0 non-null      float64
 53  Distance From Airport (kms)      0 non-null      float64
 54  Nearby Public Transport Service  0 non-null      float64
 55  Other Nearby Places              0 non-null      float64
 56  Maintenance Staff                0 non-null      float64
 57  Security Staff                   0 non-null      float64
 58  Other Facilities                 0 non-null      float64
dtypes: float64(48), object(11)
memory usage: 8.2+ MB

In [ ]:
# total number of rows
len(df)

18255

In [ ]:
# Check for missing values
df.isnull().sum()

Title                                 16
URL                                    0
City                                   0
Type                                  16
Area                                  16
Price                                 16
Purpose                               16
Location                              16
Description                         3362
Built in year                       6315
Parking Spaces                      8599
Double Glazed Windows              18255
Central Air Conditioning           18255
Central Heating                    18255
Flooring                           18255
Electricity Backup                 18255
Waste Disposal                     18255
Floors                              9889
Other Main Features                18255
Furnished                          18255
Bedrooms                              16
Bathrooms                             16
Servant Quarters                    8598
Drawing Room                       18255
Dining Room                        18255
Kitchens                            4999
Study Room                         18255
Prayer Room                        18255
Powder Room                        18255
Store Rooms                         8536
Steam Room                         18255
Lounge or Sitting Room             18255
Laundry Room                       18255
Other Rooms                        18255
Broadband Internet Access          18255
Satellite or Cable TV Ready        18255
Intercom                           18255
Community Lawn or Garden           18255
Community Swimming Pool            18255
Community Gym                      18255
First Aid or Medical Centre        18255
Day Care Centre                    18255
Kids Play Area                     18255
Barbeque Area                      18255
Mosque                             18255
Community Centre                   18255
Lawn or Garden                     18255
Sauna                              18255
Jacuzzi                            18255
Nearby Schools                     18255
Nearby Hospitals                   18255
Nearby Shopping Malls              18255
Nearby Restaurants                 18255
Distance From Airport (kms)        18255
Nearby Public Transport Service    18255
Other Nearby Places                18255
Maintenance Staff                  18255
Security Staff                     18255
Other Facilities                   18255
dtype: int64

In [ ]:
# Drop All Columns with Only Missing Values
df.dropna(axis=1, how='all', inplace=True)

In [ ]:
df.columns

Index(['Title', 'URL', 'City', 'Type', 'Area', 'Price', 'Purpose', 'Location',
       'Description', 'Built in year', 'Parking Spaces', 'Floors', 'Bedrooms',
       'Bathrooms', 'Servant Quarters', 'Kitchens', 'Store Rooms'],
      dtype='object')

In [ ]:
# statistical description of datafram
df.describe()

,Built in year,Parking Spaces,Floors,Servant Quarters,Kitchens,Store Rooms
count,11940.000000,9656.000000,8366.000000,9657.000000,13256.000000,9719.000000
mean,1967.123744,5.251833,2.393677,1.236823,1.686859,1.169565
std,1949.941225,41.917894,22.849369,0.706476,2.022453,0.495977
min,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,2020.000000,1.000000,2.000000,1.000000,1.000000,1.000000
50%,2024.000000,2.000000,2.000000,1.000000,2.000000,1.000000
75%,2025.000000,3.000000,2.000000,1.000000,2.000000,1.000000
max,202122.000000,2015.000000,2018.000000,22.000000,211.000000,18.000000

In [ ]:
# Check for total number of duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows Detected: {duplicate_count}")

# View sample duplicate entries (if any)
if duplicate_count > 0:
    print("Sample Duplicate Rows:")
    display(df[df.duplicated()].head())

# Remove duplicate rows permanently
df.drop_duplicates(inplace=True)

# Confirm removal
print(f"\n Duplicates Removed. New shape: {df.shape}")

Duplicate Rows Detected: 0

 Duplicates Removed. New shape: (18255, 17)

In [ ]:
# Check for duplicates based on these columns
df.duplicated(subset=['Title', 'Area', 'Price']).sum()

np.int64(559)

In [ ]:
# Drop duplicates based on key listing attributes
df.drop_duplicates(subset=['Title', 'Area', 'Price'], inplace=True)

# Confirm shape after cleanup
print(f"Clean dataset shape: {df.shape}")

Clean dataset shape: (17696, 17)

In [ ]:
# # # Categorical Column Analysis
# # print("\n\n. Categorical Column Analysis")

# for col in ['Price', 'Area']:

#     # Print column header
#     print(f"\nAnalysis for column: ' {col} ' ")

#     # Show unique values (categories present in the column)
#     print("\nUnique values:", df[col].unique())

#     # Show frequency count of each category
#     print("\nUnique Value counts:", df[col].value_counts())

#     print("---------------------------------------------")

In [ ]:
print("Price Unique Values :", df['Price'].nunique()) # count of distinct values
print("Price Duplicates.   :", df['Price'].duplicated().sum())

print("\nArea Unique Values:", df['Area'].nunique()) # # count of distinct values
print("Area Duplicates:    :", df['Area'].duplicated().sum())

Price Unique Values : 904
Price Duplicates.   : 16791

Area Unique Values: 216
Area Duplicates:    : 17479

In [ ]:
print("Top 10 Price Values:\n", df['Price'].value_counts().head(10))
print("Top 10 Area Values:\n", df['Area'].value_counts().head(10))

Top 10 Price Values:
 Price
35000000.0    208
25000000.0    201
100000.0      187
150000.0      179
22000000.0    175
16000000.0    173
45000000.0    171
17500000.0    170
110000.0      170
120000.0      170
Name: count, dtype: int64
Top 10 Area Values:
 Area
1361.25     3355
2722.50     2889
5445.00     2047
1905.75      847
1633.50      445
1089.00      412
2178.00      354
816.75       330
3267.00      321
10890.00     230
Name: count, dtype: int64

In [ ]:
# Clean messy columns ( e.g., remove commas, PKR symbols)
import numpy as np

def clean_price_column(series):
    cleaned = (
        series.astype(str)
              .str.replace(',', '', regex=False)
              .str.replace('PKR', '', regex=False)
              .str.replace('Rs.', '', regex=False)
              .str.strip()
              .str.lower()
    )

    # Convert Lakh and Crore to numbers
    def convert_units(value):
        try:
            if 'crore' in value:
                num = float(value.replace('crore', '').strip())
                return num * 1e7
            elif 'lakh' in value:
                num = float(value.replace('lakh', '').strip())
                return num * 1e5
            else:
                return float(value)
        except:
            return np.nan

    return cleaned.apply(convert_units)

In [ ]:

df['Price'] = clean_price_column(df['Price'])

# Preview result
print(df[['Price']].head())

        Price
0  47500000.0
1  62500000.0
2  34500000.0
3  29800000.0
4  46500000.0

In [ ]:
# Convert area units (marla/kanal/sqft → uniform sqft), if required

def clean_area_column(series):
    unit_map = {
        'marla': 272.25,
        'kanal': 5445,
        'sq yards': 9,
        'sq. yards': 9,
        'sq meter': 10.7639,
        'sq. meter': 10.7639,
        'square meter': 10.7639,
        'sq ft': 1,
        'sq. ft': 1,
        'square feet': 1
    }

    cleaned = (
        series.astype(str)
              .str.replace(',', '', regex=False)
              .str.lower()
              .str.strip()
    )

    def convert_area(value):
        for unit in unit_map:
            if unit in value:
                try:
                    num = float(value.replace(unit, '').strip())
                    return num * unit_map[unit]
                except:
                    return np.nan
        try:
            return float(value)  # If it's already in sqft
        except:
            return np.nan

    return cleaned.apply(convert_area)

In [ ]:
df['Area'] = clean_area_column(df['Area'])
df['Area'].dropna().head(10).tolist()

[1932.975,
 816.75,
 2178.0,
 2722.5,
 2722.5,
 2178.0,
 2722.5,
 1932.975,
 2994.75,
 5445.0]

In [ ]:
# # Categorical Column Analysis
# print("\n\n. Categorical Column Analysis")

# for col in df.columns:

#     # Print column header
#     print(f"\nAnalysis for column: ' {col} ' ")

#     # Show unique values (categories present in the column)
#     print("\nUnique values:", df[col].unique())

#     # Show frequency count of each category
#     print("\nUnique Value counts:", df[col].value_counts())

#     print("---------------------------------------------")

In [ ]:
# Integer count of distinct values
for column in df:
    print(column,df[column].nunique())

Title 16064
URL 17696
City 83
Type 7
Area 468
Price 1022
Purpose 2
Location 1048
Description 13437
Built in year 95
Parking Spaces 46
Floors 20
Bedrooms 23
Bathrooms 17
Servant Quarters 14
Kitchens 10
Store Rooms 10

In [ ]:
# for column in df:
#     print("Column"," ",column,"  uniquevalue  are :", df[column].nunique())
#     print(df[column].unique())
#     print("-------------------------")

In [ ]:
# df.isnull().sum()

In [ ]:
# 3. Missing Values Treatment

# Missing Values - Function
import pandas as pd

def check_missing_values(df):
    """
    Returns a DataFrame summarizing missing values in the input DataFrame.

    Columns:
    - 'Missing Values': total number of missing values in each column
    - 'Percentage (%)': percentage of missing values in each column
    """
    # 1. Total missing values in each column
    missing_counts = df.isnull().sum()

    # 2. Percentage of missing values
    missing_percent = (missing_counts / len(df)) * 100

    # 3. Combine into a single DataFrame
    missing_summary = pd.DataFrame({
        'Missing Values': missing_counts,
        'Percentage (%)': missing_percent.round(2)
    })

    # 4. Filter only columns with missing values
    missing_summary = missing_summary[missing_summary['Missing Values'] > 0]

    return missing_summary

# calling function
print("\n\nSummary of Missing Values:")

missing_info = check_missing_values(df)
print(missing_info)

Summary of Missing Values:
                  Missing Values  Percentage (%)
Title                         16            0.09
Type                          16            0.09
Area                          16            0.09
Price                         16            0.09
Purpose                       16            0.09
Location                      16            0.09
Description                 3362           18.42
Built in year               6315           34.59
Parking Spaces              8599           47.10
Floors                      9889           54.17
Bedrooms                      16            0.09
Bathrooms                     16            0.09
Servant Quarters            8598           47.10
Kitchens                    4999           27.38
Store Rooms                 8536           46.76