<a href="https://colab.research.google.com/github/raheelam98/DataAnalysis/blob/main/EDA/EDA_Sessions_RM/Data_Cleaning_Inconsistent_Data_Sec_4_RM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we're going to learn how to clean up inconsistent text entries.

Let's get started!

# Get our environment set up

The first thing we'll need to do is load in the libraries and dataset we'll be using.

In [4]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [3]:
# from google.colab import drive
#drive.mount('/content/sample_data/EDA/pakistan_intellectual_capital.csv')

In [5]:
# mounted your Drive inside Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
# list files in your EDA folder and confirm whether
!ls /content/MyDrive/EDA/

pakistan_intellectual_capital.csv

In [14]:
# modules we'll use
import pandas as pd
import numpy as np

# read in all our data
professors = pd.read_csv('/content/MyDrive/EDA/pakistan_intellectual_capital.csv')
professors

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,1974,1975,Dr. Ahmar Rashid,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,JNU,South Korea,NaN,"Electrical Impedance Tomography, Inverse algor...",NaN
1138,1975,1976,Dr. Fawad Hussain,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,Grenoble,France,NaN,"Machine Learning, Big Data Anaysis, Data Minin...",NaN
1139,1977,1978,Dr. Rashad M Jillani,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Florida Atlantic University,USA,2012.0,"Digital Multimedia Systems, Video Compression ...",NaN
1140,1979,1980,Dr. Shahabuddin Ansari,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Ghulam Ishaq Khan Institute of Science and Tec...,Pakistan,NaN,"Medical Image Processing and Analysis, Digital...",NaN
1141,1980,1981,Dr. Sajid Anwar,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Seoul National University,South Korea,NaN,"Pruning and Quantizing CNN, GPGPU,",NaN

In [15]:
# helpful modules
import fuzzywuzzy # pip install fuzzywuzzy
from fuzzywuzzy import process

In [16]:
# Basic Info
professors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1142 entries, 0 to 1141
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 1142 non-null   int64
 1   S#                                         1142 non-null   int64
 2   Teacher Name                               1142 non-null   object
 3   University Currently Teaching              1142 non-null   object
 4   Department                                 1142 non-null   object
 5   Province University Located                1142 non-null   object
 6   Designation                                1123 non-null   object
 7   Terminal Degree                            1138 non-null   object
 8   Graduated from                             1142 non-null   object
 9   Country                                    1142 non-null   object
 10  Year                                       489 non-null    float64
 11  Area of Specialization/Research Interests  623 non-null    object
 12  Other Information                          124 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 116.1+ KB

In [22]:
# Peek at the Top Rows
professors.head()

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN

In [18]:
# View All Column Names
professors.columns.tolist()

['Unnamed: 0',
 'S#',
 'Teacher Name',
 'University Currently Teaching',
 'Department',
 'Province University Located',
 'Designation',
 'Terminal Degree',
 'Graduated from',
 'Country',
 'Year',
 'Area of Specialization/Research Interests',
 'Other Information']

In [23]:
professors.columns

Index(['Unnamed: 0', 'S#', 'Teacher Name', 'University Currently Teaching',
       'Department', 'Province University Located', 'Designation',
       'Terminal Degree', 'Graduated from', 'Country', 'Year',
       'Area of Specialization/Research Interests', 'Other Information'],
      dtype='object')

In [21]:
# Check Data Types & Null Counts More Clearly
missing = professors.isnull().sum()
print(missing[missing > 0])

Designation                                    19
Terminal Degree                                 4
Year                                          653
Area of Specialization/Research Interests     519
Other Information                            1018
dtype: int64

In [20]:
# returns a count of missing (null) values in each column of the DataFrame.
professors.isnull().sum()

Unnamed: 0                                      0
S#                                              0
Teacher Name                                    0
University Currently Teaching                   0
Department                                      0
Province University Located                     0
Designation                                    19
Terminal Degree                                 4
Graduated from                                  0
Country                                         0
Year                                          653
Area of Specialization/Research Interests     519
Other Information                            1018
dtype: int64

In [24]:
#Distinct (Unique) Values
#df['ColumnName'].nunique()

professors['Teacher Name'].nunique()

1133

In [25]:
#Distinct (Unique) Values
professors['S#'].nunique()

1142

In [26]:
#Distinct (Unique) Values
professors['Unnamed: 0'].nunique()

1142

In [27]:
# check for duplicate values in a specific column of a DataFrame and
# returns a Series of boolean values:
professors['S#'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1137    False
1138    False
1139    False
1140    False
1141    False
Name: S#, Length: 1142, dtype: bool

In [29]:
# Count missing values per column:
print(professors.isnull())

#Filter rows with missing data:
professors[professors['S#'].isnull()]

      Unnamed: 0     S#  Teacher Name  University Currently Teaching  \
0          False  False         False                          False
1          False  False         False                          False
2          False  False         False                          False
3          False  False         False                          False
4          False  False         False                          False
...          ...    ...           ...                            ...
1137       False  False         False                          False
1138       False  False         False                          False
1139       False  False         False                          False
1140       False  False         False                          False
1141       False  False         False                          False

      Department  Province University Located  Designation  Terminal Degree  \
0          False                        False        False            False
1          False                        False        False            False
2          False                        False        False            False
3          False                        False        False            False
4          False                        False        False            False
...          ...                          ...          ...              ...
1137       False                        False        False            False
1138       False                        False        False            False
1139       False                        False        False            False
1140       False                        False        False            False
1141       False                        False        False            False

      Graduated from  Country   Year  \
0              False    False   True
1              False    False   True
2              False    False   True
3              False    False   True
4              False    False  False
...              ...      ...    ...
1137           False    False   True
1138           False    False   True
1139           False    False  False
1140           False    False   True
1141           False    False   True

      Area of Specialization/Research Interests  Other Information
0                                         False               True
1                                         False               True
2                                         False               True
3                                         False               True
4                                         False               True
...                                         ...                ...
1137                                      False               True
1138                                      False               True
1139                                      False               True
1140                                      False               True
1141                                      False               True

[1142 rows x 13 columns]

Empty DataFrame
Columns: [Unnamed: 0, S#, Teacher Name, University Currently Teaching, Department, Province University Located, Designation, Terminal Degree, Graduated from, Country, Year, Area of Specialization/Research Interests, Other Information]
Index: []

In [30]:
professors['S#'].duplicated().sum()

np.int64(0)

# Do some preliminary text pre-processing

We'll begin by taking a quick look at the first few rows of the data.

In [31]:
professors.head(20)

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN
5,25,26,Nausheed Saeed,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,MCS,University of Balochistan,Pakistan,2008.0,"Software Engineering, Computer Networks.",NaN
6,26,27,Shumaila Hussain,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,MS,Balochistan University of Information Technolo...,Pakistan,2011.0,"Human computer Interaction, Web Development, S...",NaN
7,27,28,Mirfa Manzoor,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Sardar Bahadur Khan Women's University,Pakistan,2009.0,"Human Computer Interaction, Web",NaN
8,28,29,Saira Mujahid,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Sardar Bahadur Khan Women's University,Pakistan,2009.0,JAVA Programming,NaN
9,29,30,Arifa Anwar,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Sardar Bahadur Khan Women's University,Pakistan,2009.0,Programming,NaN
10,101,102,Mazhar Mohsin,University of Turbat,Computer Science,Balochistan,Assistant Professor,MS,Asian Institute of Technology,Thailand,NaN,"Object Detection, Object Tracking, Pattern Rec...",NaN
11,102,103,Mukhtar Hussain,University of Turbat,Computer Science,Balochistan,Lecturer,MS,SRH Hochschule Heidelberg,germany,NaN,"Semantic Web, Machine Learning",NaN
12,104,105,Shamsa Aziz,University of Turbat,Computer Science,Balochistan,Lecturer,MS,"Institute of Business Administration,Karachi",Pakistan,NaN,Semantic Web,NaN
13,106,107,Bilal-ur-Rehman,University of Turbat,Computer Science,Balochistan,Lecturer,BE,"DUET,Karachi",Pakistan,NaN,"Computer Graphics, Digital Logic Design, Softw...",NaN
14,107,108,Balach Khan,University of Turbat,Computer Science,Balochistan,Lecturer,BS,University of Balochistan,Pakistan,NaN,"Data Structures & Algorithms, Programming",NaN
15,108,109,Pari Naz,University of Turbat,Computer Science,Balochistan,Lecturer,BS,University of Turbat,Pakistan,NaN,"Software Engineering, Theory of Automata and F...",NaN
16,110,111,Majid Iqbal Khan,"COMSATS, Islamabad Campus",Computer Science,Capital,Head of Department,PhD,University of Vienna,Austria,2009.0,"wireless sensor networks, MANETS and internet ...",NaN
17,111,112,Sohail Asghar,"COMSATS, Islamabad Campus",Computer Science,Capital,Professor,PhD,Monash University,Australia,2006.0,"Machine Learning and Data mining, decision sup...",NaN
18,114,115,Muaz A. Niazi,"COMSATS, Islamabad Campus",Computer Science,Capital,Chief Scientific Officer,Phd,University of Stirling,UK,NaN,Complex Communication Networks such as Interne...,NaN
19,115,116,Muhammad Manzoor ilahi Tamimy,"COMSATS, Islamabad Campus",Computer Science,Capital,Associate Professor,Phd,Chinese Academy of Sciences,China,NaN,"Mining Data Streams, Ubiquitous Data Mining, I...",NaN

In [32]:
# View All Column Names
professors.columns.tolist()

['Unnamed: 0',
 'S#',
 'Teacher Name',
 'University Currently Teaching',
 'Department',
 'Province University Located',
 'Designation',
 'Terminal Degree',
 'Graduated from',
 'Country',
 'Year',
 'Area of Specialization/Research Interests',
 'Other Information']

In [33]:
# dropping specific columns

professors.drop(['S#', 'Unnamed: 0','Area of Specialization/Research Interests', 'Other Information', 'Teacher Name'], axis=1, inplace=True)

# - drop([...], axis=1): Removes columns (axis=1 → column-wise).
# - inplace=True: Changes the DataFrame directly without needing to assign it back.

## Reason to Remove These Columns

These columns might be excluded during preprocessing for clarity and performance:

| **Column Name**                             | **Reason for Removal**                                                                 |
|--------------------------------------------|----------------------------------------------------------------------------------------|
| `S#`                                        | Just a serial number — adds no analytical value. Often an index or redundant row ID.  |
| `Unnamed: 0`                                | Auto-generated column from saved CSV (duplicate of index). Not useful analytically.   |
| `Area of Specialization/Research Interests` | Contains long, varied text. Hard to model without NLP techniques.                     |
| `Other Information`                         | Typically vague or unstructured (notes, commentary). Not easily quantifiable.         |
| `Teacher Name`                              | May not be necessary for grouping/statistics. Can also raise privacy considerations.  |

---

## 🎯 The Goal of Dropping Columns

- **Reduce noise**: Keep only useful variables  
- **Improve performance**: Smaller dataset = faster processing  
- **Focus analysis**: Stick to features that drive meaningful insights (e.g., university, field, publications, rank)

In [34]:
professors.columns.tolist()

['University Currently Teaching',
 'Department',
 'Province University Located',
 'Designation',
 'Terminal Degree',
 'Graduated from',
 'Country',
 'Year']

In [35]:
professors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1142 entries, 0 to 1141
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   University Currently Teaching  1142 non-null   object
 1   Department                     1142 non-null   object
 2   Province University Located    1142 non-null   object
 3   Designation                    1123 non-null   object
 4   Terminal Degree                1138 non-null   object
 5   Graduated from                 1142 non-null   object
 6   Country                        1142 non-null   object
 7   Year                           489 non-null    float64
dtypes: float64(1), object(7)
memory usage: 71.5+ KB

In [36]:
# Count of Each Unique Value in a Series (column)
# df['ColumnName'].value_counts()
professors["Terminal Degree"].value_counts()

Terminal Degree
MS                                463
PhD                               363
BS                                 93
MSc                                37
MCS                                20
Mphil                              17
M.E                                14
Post Doc                           13
M.Phil                             13
MSCS                               13
Phd                                12
ME                                 11
MBA                                11
BE                                  6
PostDoc                             6
BCS                                 4
MPhil                               4
MA                                  3
M.Sc                                3
MCIT                                3
MSSE                                3
Bachelors                           3
Ph.D                                2
MIT                                 2
MSC                                 2
MSIT                                2
Masters                             1
BSCS                                1
M.Phil leading to PhD               1
BIT                                 1
BSC                                 1
Master                              1
BSIT                                1
B.E                                 1
M.Eng                               1
M.A                                 1
B.Ed                                1
MSTN                                1
Doctor of Professional Studies      1
BSc                                 1
BA                                  1
Name: count, dtype: int64

In [37]:
# Loop through each column in the DataFrame
for column in professors:

    # Print the name of the column
    print("Column", " ", column, "  uniquevalue  are :", professors[column].nunique())

    # Print the unique values present in that column
    print(professors[column].unique())

    # Print a separator line for readability between columns
    print("-------------------------")

# what this code do :-loops through every column in the professors DataFrame.
# For each column, it:

# Shows how many unique values it has using .nunique().
# Lists those actual unique values using .unique().
# Separates each output visually for clarity.

Column   University Currently Teaching   uniquevalue  are : 63
['University of Balochistan' "Sardar Bahadur Khan Women's University"
 'University of Turbat' 'COMSATS, Islamabad Campus'
 'National University of Sciences and Technology' 'RIPHAH International'
 'FAST-NU(Islamabad)' 'International Islamic University,Islamabad'
 'National University of Modern Languages' 'Air University'
 'Bahria University,Islamabad'
 'Capital University of Science and Technology'
 'Pakistan Institute of Engineering and Applied Sciences'
 'University of Sargodha,Mandi Bahauddin Campus' 'NAML-Mianwali'
 'University of Lahore-PakPattan' 'University of Sahiwal'
 'Barani Institute of Information and Technology'
 'Fatima Jinnah Women University' 'FAST(Faisalabad)'
 'University of Central Punjab' 'Lahore Garrison University'
 'Punjab University College of Information and Technology' 'FAST(Lahore)'
 'Information Technology University'
 'Lahore University of Management Sciences' 'Virtual University'
 'University of Management and Technology' 'Minhaj University Lahore'
 'Beaconhouse National University'
 'Shaheed Zulfikar Ali Bhutto Institute of Science and Technology'
 'QUAID-E-AWAM UNIVERSITY OF ENGINEERING, SCIENCE & TECHNOLOGY,NAWABSHAH\n'
 'Shah Abdul Latif University, Khairpur'
 'Shaheed Benazir Bhutto University,Shaheed Benazirabad\n'
 'University of Sindh' 'FAST(Karachi)' 'University of Karachi' 'NED,UET'
 'Institute of Business Administration, Karachi\xa0'
 'Institute of Business Administration,Sukkur' 'ISRA University'
 'Sir Syed University of Engineering and Technology'
 'Jinnah University for Women' 'DHA Suffa University'
 'PAF-Karachi Institute of Economics and Technology'
 'Mohammad Ali Jinnah University' 'Habib University'
 'Islamia University Bhawalpur' 'University of Chakwal'
 'Government College University Faisalabad'
 'National Textile University,Faisalabad'
 'NFC Institute of Engineering and Fertilizer Research'
 'Riphah University,Faisalabad' 'Gift University'
 'Punjab University,Gujranwala Campus' 'University of Gujrat'
 'University of Peshawar'
 'University of Engineering and Technology,Peshawar'
 'University of Agriculture,Peshawar' 'FAST,Peshawar' 'City University'
 'Abasyn University' 'Ghulam Ishaq Khan Institute']
-------------------------
Column   Department   uniquevalue  are : 17
['Computer Science & IT' 'Computer Science' 'Computing'
 'Computer Science and Software Engineering'
 'Computer and Information Sciences' 'Computer Science and IT'
 'Software Engineering' 'Computer Sciences' 'Information Technology'
 'CS & IT' 'School of Information and Technology'
 'Institute of Mathematics & Computer Science'
 'ENGINEERING, SCIENCE & TECHNOLOGY' 'Computer Engineering'
 'Computing & Information Sciences' 'FACULTY OF COMPUTING & ENGINEERING'
 'Computer Science and Engineering']
-------------------------
Column   Province University Located   uniquevalue  are : 5
['Balochistan' 'Capital' 'Punjab' 'Sindh' 'KPK']
-------------------------
Column   Designation   uniquevalue  are : 46
['Assistant Professor' 'Lecturer' 'Head of Department' 'Professor'
 'Chief Scientific Officer' 'Associate Professor' 'Dean'
 'Professor/Associate Dean (Research)' nan 'Professor/HoD'
 'Associate Professor/Chairman' 'Assistant Professor/Acting Chairperson'
 'Senior Assistant Professor' 'Senior Lecturer' 'Jr.Lecturer'
 'Professor/Dean' 'Head' 'Controller of Examinations'
 'Associate Professor/HoD' 'HEC Approved PhD Supervisor' 'Instructor'
 'Principal' 'Adjunct Professor' 'Vice Chancellor'
 'Associate Professor/Chairperson' 'Associate Professor/Chair'
 'Tutor/Instructor' 'Research Associate' 'Chairman' 'I.T Manager'
 'Assistant Professor/HoD' 'Vice President/Dean' 'Professor/Chairman'
 'Professor/Director & Registrar' 'Professor/Co-Chairman'
 'Professor/Chairperson' 'Director' 'Permanent Faculty' 'Faculty Member'
 'Assistant Professor/Director' 'Lab Engineer'
 'Assistant Professor/Chairman' 'Assistant Professor/Principal'
 'Teaching Fellow' 'Assistant Professor/Incharge Department'
 'Departmental Assistant' 'Teaching Assistant']
-------------------------
Column   Terminal Degree   uniquevalue  are : 41
['PhD' 'BS' 'MCS' 'MS' 'BE' 'Phd' nan 'PostDoc' 'Masters' 'MBA' 'MSc'
 'BIT' 'MA' 'Mphil' 'MPhil' 'Post Doc' 'MIT' 'BSC' 'MSCS' 'BSIT' 'MSC'
 'M.Phil' 'Master' 'Bachelors' 'M.Phil leading to PhD' 'BSCS' 'M.Sc' 'BCS'
 'ME' 'B.Ed' 'M.A' 'M.Eng' 'MCIT' 'B.E' 'M.E' 'MSIT' 'Ph.D' 'MSSE' 'MSTN'
 'Doctor of Professional Studies' 'BSc' 'BA']
-------------------------
Column   Graduated from   uniquevalue  are : 347
['Asian Institute of Technology'
 'Balochistan University of Information Technology, Engineering and Management Sciences'
 'University of Balochistan' "Sardar Bahadur Khan Women's University"
 'SRH Hochschule Heidelberg'
 'Institute of Business Administration,Karachi' 'DUET,Karachi'
 'University of Turbat' 'University of Vienna' 'Monash University'
 'University of Stirling' 'Chinese Academy of Sciences'
 'University of Innsbruck' 'Vienna University of Technology'
 'University of Paris-Est' 'The University of Cambridge'
 'Harbin Institute of Technology' 'University of Nice, Sophia Antipolis'
 'The University of York' 'Galilée - Université Paris 13'
 'University of Bedfordshire' 'North Dakota State University'
 'Kyungpook National University' 'The University of Manchester'
 'National University of Sciences and Technology'
 'FAST– National University of Computer and Emerging Sciences'
 'Capital University of Science & Technology' 'Gomal University'
 'University of Malaya' 'KTH Royal Institute of Technology'
 'University of Technology' 'COMSATS Institute of Information Technology'
 'Government College University' 'Mohammad Ali Jinnah University'
 'Shaheed Zulfikar Ali Bhutto Institute of Science and Technology'
 'Blekinge Institute of Technology' 'University of Grenoble'
 'Politecnico di Torino' '\xa0University of Missouri, KC'
 'University of Bonn' 'University of Paris' 'The University of Leeds'
 '\xa0University of Windsor'
 '\xa0National University of Sciences and Technology-NIIT'
 'University of Trento' 'Stockholm University'
 'University of New South Wales, Sydney' 'Kingston University London'
 'Griffith University' 'University of Salford' 'Loughborough University'
 'International Islamic University,Islamabad'
 'University of Central Missouri' 'Riphah International University'
 'University of BedfordShire' 'University of Illinois'
 'University Of Oslo' 'Nancy 2 University' 'University of Limerick'
 'Ghulam Ishaq Khan Institute of Science and Technology'
 'University Of Waterloo' 'University of Stuttgart'
 'Liverpool John Moores University' 'University Of Caen'
 'Paris Tech University of Eurecom' 'University Of Salford'
 'Lahore University of Management Sciences'
 'Dresden University Of Technology, Dresden\xa0'
 'COMSATS Institute of Information Technology,Vehari'
 'COMSATS Institute of Information Technology,Wah Cantt' 'TU Berlin'
 'FAST– National University of Computer and Emerging Sciences,Islamabad'
 'Tsinghua University' 'The University of Auckland' 'IQRA University'
 'Universiti Teknologi PETRONAS'
 'COMSATS Institute of Information Technology,Islamabad'
 'Razak School of Engineering and Advanced Technology, Universiti Teknologi Malaysia (UTM)'
 'National University of Modern Languages'
 'University of Engineering and Technology'
 'University Institute of Information Technology'
 'University of Arid Agriculture' 'Quaid-i-Azam University'
 'Queen Mary University of London'
 'Pakistan Institute of Engineering and Applied Sciences'
 'Pohang University of Science and Technology' 'Uppsala University'
 'Kyung Hee University' 'University of Liverpool'
 'University of Sunderland' 'Mid Sweden University'
 'Bahria University,Islamabad' 'Chosun University' 'University of Sussex'
 'Paris Descartes University' 'University of Leicester'
 'University of Porto' 'University of Manchester'
 'Université Henri Poincaré, Nancy 1,' 'Bahria University'
 'Centre for Advanced Studies in Engineering'
 'Norwegian University of Science and Technology (NTNU),'
 'The Islamia University of Bahawalpur' 'Universiti Technologi'
 'California State University' 'University of Genova'
 'University of Engineering and Technology,Taxila'
 'University of\xa0Liverpool John Moores University' 'Guildford'
 'University of Bradford' 'Graz University of Technology'
 'Huazhong University of Science and Technology (HUST), Wuhan'
 'University of Konstanz'
 'National University of Modern Languages,Islamabad'
 'FAST– National University of Computer and Emerging Sciences,Lahore'
 'Gwangju Institute of Science and Technology' 'University of Birmingham'
 'Manchester University' 'Beijing Institute of Technology'
 'University of Paisley'
 'Univ of Porto/Univ of Aveiro Portugal/Uni of Minho'
 'University of Peshawar' 'Universität Salzburg'
 'Colorado State University' 'University of Virginia'
 'University of Orleans' 'Zhejiang University' 'University of Leeds'
 'Foundation University' 'Barani Institute of Information Technology'
 'Abasyn University' 'Pir Mehr Ali Shah Arid Agriculture University'
 'Preston' 'University of Bergen' 'Universtiy of Lahore'
 'HITEC University,Taxila' 'Allama Iqbal Open University'
 'University of Wales,Aberystwyth' '\xa0University of Bonn'
 '\xa0Hongik University'
 'Skolkovo Institute of Science and Technology,\xa0'
 'Agricultural University Peshawar' 'National Textile University'
 'FAST– National University of Computer and Emerging Sciences,Chiniot-Faisalabad'
 'FAST– National University of Computer and Emerging Sciences,Peshawar'
 '\xa0Boston University' 'Brunel University'
 'George Washington University' 'University of the Punjab'
 '\xa0University of Bedfordshire' 'University Of Southern California'
 'Beihang University' 'Institute of Business Administration'
 'Abdus Salam School of Mathematical Sciences,GC University'
 'Linköping University'
 'National College of Business Administration and Economics'
 'Åbo Akademi University,' 'University of Central Punjab'
 'University of Ulm' 'University of Agriculture'
 'University of Notre Dame Indiana\xa0'
 'Punjab University College of Information Technology'
 'Ilmenau University of Technology' 'Iowa State University'
 'Vrije University, Amsterdam' 'Columbia University'
 'University of Freiburg' 'Delft University of Technology'
 'University of Texas at Arlington (UTA)' 'University of Turin'
 'University of Central Florida' 'Saarland University'
 'Oxford Brookes University' 'Information Technology University (ITU)'
 'University of Canterbury' 'University of Patras'
 'Middle East Technical University' 'University of Bristol'
 'University of Southern California' 'Northeastern University,Boston'
 'Purdue University' 'University of Plymouth'
 'University of South Australia' 'Stanford University'
 'Chalmers University of Technology'
 'Massachusetts Institute of Technology' 'Sapienza University of Rome'
 'Eindhoven University of Technology (TU/e)'
 'United Nations University International Institute for Software Technology (UNU-IIST)'
 'Georgetown University,DC' 'RWTH Aachen University'
 'Rutgers State University of New Jersey, NJ' 'University of Florida'
 'Technical University of Braunschweig'
 'Carnegie Mellon University, Pittsburgh' 'The Ohio State University'
 'National University of Singapore' 'University of British Columbia'
 'University of Pittsburgh' 'The State University of New Jersey'
 'The University of Texas at Austin'
 'Imperial College, University of London' 'University of Colorado\xa0'
 'University of Bath' 'Tilburg University'
 'Pompeu Fabra University Barcelona'
 'University of Management and Technology'
 'COMSATS Institute of Information Technology,Lahore'
 'University of Agriculture, Faisalabad\xa0'
 'University of Engineering & Technology'
 'University of Agriculture, Faisalabad'
 'Fatima Jinnah Women University, Rawalpindi'
 'Kohat University of Science & Technology, Kohat'
 'Virtual University of Pakistan' 'Bahauddin Zakariya University'
 'University of the Punjab,Gujranwala'
 'Lahore College for Women University' 'Superior University, Lahore'
 'Shaheed Zulfikar Ali Bhutto Institute of Science and Technology,Islamabad'
 'University of South Florida' 'Politecnico di Milano'
 'Abdul Wali Khan University, Mardan' 'University of Lahore'
 'Minhaj University Lahore' 'Lahore Leads University'
 'Middlesex University' 'Beijing Institute of Technology Beijing'
 'Beaconhouse National University' 'Hamdard University' 'University Paris'
 'Sindh University' 'NED University of Engineering And Technology'
 'Staffordshire University' 'DePaul University, Chicago'
 'University of Kent' 'Mehran University of Engineering & Technology'
 'Quaid-e-Awam University of Engineering, Science & Technology'
 'Shah Abdul Latif University, Khairpur' 'Sindh Agriculture University'
 'Swansea' 'University of Shanghai for Science and Technology'
 'Griffith University,Nathan Campus' 'University of Essex'
 'Xiamen university' 'Wayne State University'
 'The Queens University of Belfast' 'Sungkyunkwan University'
 'Nanyang Tech University' "Universite d'Evry Val d'Essonne"
 'Sir Syed University of Engineering and Technology'
 'New York Institute of Technology' 'Fedral Urdu University'
 'ISRA University' 'University of Karachi' 'South Asian University'
 'Capital University of Science and Technology'
 'University of Manchester Institute of Science and Technology'
 'The University of Birmingham'
 'Max Planck Institute for Computer Science' 'George Mason University'
 'University of Southampton' 'Temple University' 'University of Bayreuth'
 'Muroran Institute of Technology,Hokkaido' 'University of Bologna'
 'International Islamic University'
 'PAF-Karachi Institute of Economics and Technology'
 'Institute of Business Administration,Sukkur' 'Myongji University'
 'State University of New York System' 'SSindh Agriculture University'
 'London University' 'Universiti Putra Malaysia Putra'
 'University of Rome Tor Vergata' 'University of Mississippi\xa0'
 'University of Wales' 'University of Northampton'
 'University of Abertay Dundee'
 'Biztek Institute Of Business & Technology,Karachi'
 'University of Surrey' 'Jinnah University for Women'
 '\xa0Nanyang Technological University' 'Tokyo Institute of Technology'
 'NCSU' 'Usman Institute of Technology' 'Hanyang University, Ansan' 'BUKC'
 'Universtiy of Karachi' 'Pace University, New York' 'INSA de Lyon, Rhone'
 'University of Dundee' 'Illinois Institute of Technology'
 'City University of Science and Technology'
 'Usman Institute of Technology (Hamdard University)'
 'University of Malaga' 'Manchester Metropolitan University'
 'Kyushu University,Fukuoka'
 'King Abdullah University of Science and Technology'
 'INRIA Saclay Ile-de-France' 'Université de la Rochelle'
 'University of South Brittany' 'Aston University, Birmingham'
 'University of Agriculture Faisalabad' 'Hamburg University of Technology'
 'Government College University, Faisalabad' 'JKU' 'University of Oviedo'
 'Beijing University of Posts & Telecommunications'
 'Government College University,Faisalabad' 'Nottingham Trent University'
 'University of Glasgow' 'Coventry University'
 'Riphah International University,Faisalabad'
 'Australian National University, Caneberra'
 'Swedish University of Agricultural Sciences, Uppsala'
 'University of Gujrat' 'IQRA University,Islamabad' 'Jonkoping University'
 'Colorado Technical University' 'Cranfield University'
 'Technical University of Graz' 'University of York'
 'Brock University Canada' 'University of Westminster'
 'University of Saarland' 'The University of Queensland'
 'University of Rochester' 'Islamia College University'
 'IBMS KP Agricultural University Peshawar' 'University of Kuala Lumpur'
 'University of Regina' 'TU Wien' 'Swinburne University Of Technology'
 'Institute Of Managment Sciences, Peshawar'
 'Universiti Tun Hussein Onn Malaysia'
 'Institute of Management Sciences, Peshawar' 'University of Huddersfield'
 'University of Engineering and Technology,Peshawar'
 'IQRA University,Karachi' 'John Moorse University, Liverpool'
 'CECOS University of Information Technology and Emerging Sciences,Peshawar'
 'University of the West Scotland' 'Concordia University,Montreal' 'JNU'
 'Grenoble' 'Florida Atlantic University' 'Seoul National University']
-------------------------
Column   Country   uniquevalue  are : 35
['Thailand' 'Pakistan' 'germany' 'Austria' 'Australia' 'UK' 'China'
 'France' 'USofA' 'SouthKorea' 'Malaysia' 'Sweden' 'Italy' 'Canada'
 'Norway' 'Ireland' 'New Zealand' 'Urbana' 'Portugal' 'Russian Federation'
 'USA' 'Finland' 'Netherland' 'Germany' 'Greece' 'Turkey' 'South Korea'
 'Macau' 'Singapore' 'Spain' 'Japan' 'HongKong' 'Saudi Arabia' 'Mauritius'
 'Scotland']
-------------------------
Column   Year   uniquevalue  are : 32
[  nan 2005. 2008. 2011. 2009. 2006. 2007. 2010. 2012. 2014. 2013. 2016.
 2003. 2017. 2015. 2002. 1983. 2000. 1997. 2018. 2004. 1991. 1995. 1999.
 1996. 1994. 1993. 1988. 1992. 1985. 1987. 1990. 2001.]
-------------------------

Say we're interested in cleaning up the "Country" column to make sure there's no data entry inconsistencies in it. We could go through and check each row by hand, of course, and hand-correct inconsistencies when we find them. There's a more efficient way to do this, though!

In [38]:
# Distinct (Unique) Values
#df['ColumnName'].nunique()

professors['Department'].unique()

array(['Computer Science & IT', 'Computer Science', 'Computing',
       'Computer Science and Software Engineering',
       'Computer and Information Sciences', 'Computer Science and IT',
       'Software Engineering', 'Computer Sciences',
       'Information Technology', 'CS & IT',
       'School of Information and Technology',
       'Institute of Mathematics & Computer Science',
       'ENGINEERING, SCIENCE & TECHNOLOGY', 'Computer Engineering',
       'Computing & Information Sciences',
       'FACULTY OF COMPUTING & ENGINEERING',
       'Computer Science and Engineering'], dtype=object)

In [42]:
# get all the unique values in the 'Country' column

# Convert all text in the 'Department' column to lowercase
# This ensures consistency—for example, "Physics" and "PHYSICS" become "physics"
print('All Department are in lower case')
professors['Department'] = professors['Department'].str.lower()

# Extract all unique department names from the column
# This helps us understand the diversity or duplication in department naming
print('Extract unique department name')
departments = professors['Department'].unique()


# sort them alphabetically and then take a closer look
# Sort the list alphabetically for easy scanning or debugging
print('Sort the list alphabetically')
departments.sort()

# View the sorted list of unique department names
print('View the sorted list of unique department names\n')
departments

All Department are in lower case
Extract unique department name
Sort the list alphabetically
View the sorted list of unique department names

array(['computer and information sciences', 'computer engineering',
       'computer science', 'computer science & it',
       'computer science and engineering', 'computer science and it',
       'computer science and software engineering', 'computer sciences',
       'computing', 'computing & information sciences', 'cs & it',
       'engineering, science & technology',
       'faculty of computing & engineering', 'information technology',
       'institute of mathematics & computer science',
       'school of information and technology', 'software engineering'],
      dtype=object)

In [45]:
print('Get all uniques country names in alphabetical order\n')

# get all the unique values in the 'Country' column
countries = professors['Country'].unique()

# sort them alphabetically and then take a closer look
countries.sort()
countries

Get all uniques country names in alphabetical order

array(['Australia', 'Austria', 'Canada', 'China', 'Finland', 'France',
       'Germany', 'Greece', 'HongKong', 'Ireland', 'Italy', 'Japan',
       'Macau', 'Malaysia', 'Mauritius', 'Netherland', 'New Zealand',
       'Norway', 'Pakistan', 'Portugal', 'Russian Federation',
       'Saudi Arabia', 'Scotland', 'Singapore', 'South Korea',
       'SouthKorea', 'Spain', 'Sweden', 'Thailand', 'Turkey', 'UK', 'USA',
       'USofA', 'Urbana', 'germany'], dtype=object)

In [53]:
print('Get all unique country names in lowercase\n.')

countries = professors['Country'].str.lower()

# sort them alphabetically
#countries.sort()

# only unique country name
countries.unique()

#countries

Get all unique country names in lowercase
.

array(['thailand', 'pakistan', 'germany', 'austria', 'australia', 'uk',
       'china', 'france', 'usofa', 'southkorea', 'malaysia', 'sweden',
       'italy', 'canada', 'norway', 'ireland', 'new zealand', 'urbana',
       'portugal', 'russian federation', 'usa', 'finland', 'netherland',
       'greece', 'turkey', 'south korea', 'macau', 'singapore', 'spain',
       'japan', 'hongkong', 'saudi arabia', 'mauritius', 'scotland'],
      dtype=object)

In [54]:
# RM
print('Get all unique country names in lowercase and sort them in alphabetical order.\n')

# get all the unique values in the 'Country' column

# Convert all text in the column to lowercase
professors['Country'] = professors['Country'].str.lower()

# Extract all unique country names from the column
country = professors['Country'].unique()


# sort them alphabetically and then take a closer look
country.sort()

# View the sorted list of unique country names
country

Get all unique country names in lowercase and sort them in alphabetical order.

array(['australia', 'austria', 'canada', 'china', 'finland', 'france',
       'germany', 'greece', 'hongkong', 'ireland', 'italy', 'japan',
       'macau', 'malaysia', 'mauritius', 'netherland', 'new zealand',
       'norway', 'pakistan', 'portugal', 'russian federation',
       'saudi arabia', 'scotland', 'singapore', 'south korea',
       'southkorea', 'spain', 'sweden', 'thailand', 'turkey', 'uk',
       'urbana', 'usa', 'usofa'], dtype=object)

In [58]:
# get the top 10 closest matches to "cs"

print('Get top 10 closest matches to  cs\n')

#  Use fuzzy string matching to find the closest matches to the query "computer sciences"
matchesdep = fuzzywuzzy.process.extract("computer sciences", departments, limit=20)

# View the top 20 best-matching department names from the dataset
matchesdep

Get top 10 closest matches to  Computer Sciences

[('computer sciences', 100),
 ('computer science', 97),
 ('institute of mathematics & computer science', 87),
 ('computer and information sciences', 86),
 ('computer science and engineering', 86),
 ('computer science and software engineering', 86),
 ('computing & information sciences', 86),
 ('computer science & it', 85),
 ('computer science and it', 80),
 ('computer engineering', 65),
 ('computing', 62),
 ('engineering, science & technology', 53),
 ('faculty of computing & engineering', 50),
 ('cs & it', 34),
 ('software engineering', 32),
 ('information technology', 31),
 ('school of information and technology', 30)]

In [59]:
# get the top 10 closest matches to "south korea"
matchesdep = fuzzywuzzy.process.extract("computer", departments, limit=15)

# take a look at them
matchesdep
#percentage 68%

[('computer and information sciences', 90),
 ('computer engineering', 90),
 ('computer science', 90),
 ('computer science & it', 90),
 ('computer science and engineering', 90),
 ('computer science and it', 90),
 ('computer science and software engineering', 90),
 ('computer sciences', 90),
 ('institute of mathematics & computer science', 90),
 ('computing', 71),
 ('computing & information sciences', 68),
 ('faculty of computing & engineering', 68),
 ('school of information and technology', 43),
 ('engineering, science & technology', 34),
 ('information technology', 34)]

In [60]:
#Terminal Degree
# get the top 10 closest matches to "south korea"
matchesdep = fuzzywuzzy.process.extract('BE',Terminal Degree,limit=15)

# take a look at them
matchesdep
#percentage 68%

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-60-3404763809.py, line 3)

In [62]:
matchesdep = fuzzywuzzy.process.extract('BE', professors['Terminal Degree'], limit=15)
matchesdep

[('BE', 100, 13),
 ('BE', 100, 695),
 ('BE', 100, 700),
 ('BE', 100, 822),
 ('BE', 100, 870),
 ('BE', 100, 927),
 ('B.E', 80, 765),
 ('B.Ed', 67, 671),
 ('BS', 50, 4),
 ('BS', 50, 7),
 ('BS', 50, 8),
 ('BS', 50, 9),
 ('BS', 50, 14),
 ('BS', 50, 15),
 ('BS', 50, 101)]

In [63]:
# get all the unique values in the 'Country' column
countries = professors['Country'].unique()

# sort them alphabetically and then take a closer look
countries.sort()
countries

array(['australia', 'austria', 'canada', 'china', 'finland', 'france',
       'germany', 'greece', 'hongkong', 'ireland', 'italy', 'japan',
       'macau', 'malaysia', 'mauritius', 'netherland', 'new zealand',
       'norway', 'pakistan', 'portugal', 'russian federation',
       'saudi arabia', 'scotland', 'singapore', 'south korea',
       'southkorea', 'spain', 'sweden', 'thailand', 'turkey', 'uk',
       'urbana', 'usa', 'usofa'], dtype=object)

Just looking at this, I can see some problems due to inconsistent data entry: ' Germany', and 'germany', for example, or ' New Zealand' and 'New Zealand'.

The first thing I'm going to do is make everything lower case (I can change it back at the end if I like) and remove any white spaces at the beginning and end of cells. Inconsistencies in capitalizations and trailing white spaces are very common in text data and you can fix a good 80% of your text data entry inconsistencies by doing this.

In [64]:
# convert to lower case
professors['Country'] = professors['Country'].str.lower()
# remove trailing white spaces
professors['Country'] = professors['Country'].str.strip()

print(professors['Country'])

0          thailand
1          thailand
2          thailand
3          thailand
4          pakistan
           ...
1137    south korea
1138         france
1139            usa
1140       pakistan
1141    south korea
Name: Country, Length: 1142, dtype: object

In [65]:
# get all the unique values in the 'Country' column
countries = professors['Country'].unique()

# sort them alphabetically and then take a closer look
countries.sort()
countries

array(['australia', 'austria', 'canada', 'china', 'finland', 'france',
       'germany', 'greece', 'hongkong', 'ireland', 'italy', 'japan',
       'macau', 'malaysia', 'mauritius', 'netherland', 'new zealand',
       'norway', 'pakistan', 'portugal', 'russian federation',
       'saudi arabia', 'scotland', 'singapore', 'south korea',
       'southkorea', 'spain', 'sweden', 'thailand', 'turkey', 'uk',
       'urbana', 'usa', 'usofa'], dtype=object)

Next we're going to tackle more difficult inconsistencies.

# Use fuzzy matching to correct inconsistent data entry

Alright, let's take another look at the 'Country' column and see if there's any more data cleaning we need to do.

---

---

---

---

---

---

It does look like there is another inconsistency: 'southkorea' and 'south korea' should be the same.

We're going to use the [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) package to help identify which strings are closest to each other. This dataset is small enough that we could probably could correct errors by hand, but that approach doesn't scale well. (Would you want to correct a thousand errors by hand? What about ten thousand? Automating things as early as possible is generally a good idea. Plus, it’s fun!)

> **Fuzzy matching:** The process of automatically finding text strings that are very similar to the target string. In general, a string is considered "closer" to another one the fewer characters you'd need to change if you were transforming one string into another. So "apple" and "snapple" are two changes away from each other (add "s" and "n") while "in" and "on" and one change away (rplace "i" with "o"). You won't always be able to rely on fuzzy matching 100%, but it will usually end up saving you at least a little time.

Fuzzywuzzy returns a ratio given two strings. The closer the ratio is to 100, the smaller the edit distance between the two strings. Here, we're going to get the ten strings from our list of cities that have the closest distance to "south korea".

We can see that two of the items in the cities are very close to "south korea": "south korea" and "southkorea". Let's replace all rows in our "Country" column that have a match of > 95 with "south korea".

To do this, I'm going to write a function. (It's a good idea to write a general purpose function you can reuse if you think you might have to do a specific task more than once or twice. This keeps you from having to copy and paste code too often, which saves time and can help prevent mistakes.)

Function Definition:

replace_matches_in_column(df, column, string_to_match, min_match=95): This function takes four parameters:
df: The dataframe where replacements will occur.
column: The column within the dataframe where you want to check for matches.
string_to_match: The string you want to find matches for.
min_match: The minimum similarity percentage to consider a string a match (default is 95%).
Extract Unique Strings:

strings = df[column].unique(): Retrieves all unique values from the specified column of the dataframe.
Find Close Matches:

matches = fuzzywuzzy.process.extract(string_to_match, strings, limit=5): Uses fuzzy string matching to find the top 5 strings from strings that are most similar to string_to_match.
Filter Matches by Similarity Threshold:

close_matches = [matches[0] for matches in matches if matches[1] >= min_match]: Filters out the matches to include only those with a similarity score greater than or equal to min_match. It creates a list of just these matching strings.
Identify Rows with Close Matches:

rows_with_matches = df[column].isin(close_matches): Creates a boolean series that is True for rows where the value in the specified column is in the close_matches list.
Replace Matched Rows:

df.loc[rows_with_matches, column] = string_to_match: Replaces the values in the matched rows’ specified column with string_to_match.
Completion Message:

print("All done!"): Prints a message indicating that the function has completed its execution.

Now that we have a function, we can put it to the test!