<a href="https://colab.research.google.com/github/raheelam98/DataAnalysis/blob/main/EDA/EDA_Sessions_RM/EDA_Session_01_RM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Panadas - User Guide](https://pandas.pydata.org/docs/user_guide/index.html)

In [ ]:
# Mount Google Drive:
# from google.colab import drive
# df = drive.mount('/content/drive')

### Task
Analyze the data in "/content/sample_data/ai_adoption_dataset.csv" using pandas, including reading the data, performing basic analysis, grouping, and binning.

### Load the dataset

#### Subtask:
Load the dataset from the provided CSV file into a pandas DataFrame.

In [5]:
import pandas as pd

#df = pd.read_csv("/content/sample_data")

df = pd.read_csv("/content/sample_data/EDA/ai_adoption_dataset.csv")

In [7]:
df

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,LxeKzQFbPvhxXUSgPVlLLJ pUFaicjCgiMtAmsTjovkrdE...,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,IOQtQoSKdSmiXRsUKpjXjXZgQohymFkVUvOASXlEnVsIOS...,45-54,SME
...,...,...,...,...,...,...,...,...,...
144995,Australia,Agriculture,Midjourney,86.93,7921,2023,PxWkyTVwSNPoTXjsKzjbAFEfyJ MdgY CXjvSrkkHOTGcb...,18-24,SME
144996,Germany,Education,Midjourney,51.99,6301,2024,PtOmfGyWyZueDERRioCvbNgXomcpNNLFUjRuMEqeMrqR L...,45-54,SME
144997,USA,Finance,Stable Diffusion,47.35,4726,2023,VQuOdOKjRhchmEFrzvGlqsGOc fbTXzuzQzswt pZTCmhx...,45-54,Startup
144998,USA,Retail,ChatGPT,31.87,2481,2024,IRFOudTsoPrlrKypvToOx llYkLoLqrw EMHOtyAKmqXq...,25-34,Enterprise
144999,Canada,Technology,Claude,96.84,6479,2024,pwVBio hjlquPxOkabYZsvNwXFWresQdMGmeqmBicAbHzo...,35-44,Enterprise

In [6]:
# Show number of rows and columns - RM
df.shape

(145000, 9)

In [ ]:
# Show column names - RM
df.columns

Index(['country', 'industry', 'ai_tool', 'adoption_rate', 'daily_active_users',
       'year', 'user_feedback', 'age_group', 'company_size'],
      dtype='object')

In [ ]:
# Show general info (data types, non-null counts) - RM
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145000 entries, 0 to 144999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   country             145000 non-null  object
 1   industry            145000 non-null  object
 2   ai_tool             145000 non-null  object
 3   adoption_rate       145000 non-null  float64
 4   daily_active_users  145000 non-null  int64
 5   year                145000 non-null  int64
 6   user_feedback       145000 non-null  object
 7   age_group           145000 non-null  object
 8   company_size        145000 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 10.0+ MB

In [ ]:
# Show summary statistics for numerical columns - RM
df.describe()

       adoption_rate  daily_active_users           year
count  145000.000000       145000.000000  145000.000000
mean       49.873025         5039.302683    2023.703117
std        28.842523         2858.124918       0.456886
min         0.000000          100.000000    2023.000000
25%        24.930000         2566.000000    2023.000000
50%        49.760000         5036.000000    2024.000000
75%        74.840000         7515.000000    2024.000000
max       100.000000         9999.000000    2024.000000

In [22]:
# First 1000 rows - RM
df.head(100)

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,LxeKzQFbPvhxXUSgPVlLLJ pUFaicjCgiMtAmsTjovkrdE...,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,IOQtQoSKdSmiXRsUKpjXjXZgQohymFkVUvOASXlEnVsIOS...,45-54,SME
...,...,...,...,...,...,...,...,...,...
95,China,Agriculture,Stable Diffusion,85.34,2715,2023,kXNajsJ zoOxAFntfQmOAWFQXFcqzgSxhsuhkdaBBQbHaM...,35-44,Startup
96,China,Agriculture,Midjourney,86.45,9812,2023,sXuDg nsajcFsUWgbVDjtHFQGuGExWNrQydhnZAhDCQXhx...,55+,Startup
97,Australia,Manufacturing,Midjourney,29.51,2667,2024,RTYBkhFpfBeyCDHKsgVbfhfMxwNhMEpAZsclhIjhJgNTch...,35-44,Enterprise
98,Australia,Transportation,Midjourney,64.96,1890,2024,cHBacNuSqWVxBRGMYwRJdIeUIwBQiPMDRTCCWBaLiHqevZ...,18-24,Enterprise
99,India,Retail,ChatGPT,58.54,7052,2023,hVmbNudrOCBljdOkYqjUnDrbciYI xbqQbcAJCPzPtVdhy...,25-34,SME

### Perform basic data analysis

#### Subtask:
Display the first few rows, check the data types of columns, and get a summary of the dataset's statistics.

**Reasoning**:
Display the first few rows, check the data types, and get a statistical summary of the DataFrame as requested by the instructions.

In [9]:
display(df.head()) # head of the table- first 5 rows

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,LxeKzQFbPvhxXUSgPVlLLJ pUFaicjCgiMtAmsTjovkrdE...,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,IOQtQoSKdSmiXRsUKpjXjXZgQohymFkVUvOASXlEnVsIOS...,45-54,SME

In [11]:
display(df.head(8)) #df.tail()

,country,industry,ai_tool,adoption_rate,daily_active_users,year,user_feedback,age_group,company_size
0,USA,Technology,ChatGPT,40.45,2461,2023,YyvLXOFyevRMSvJtkXodLvgejiqQNvSOZfeeJASDOVTxwm...,35-44,Startup
1,France,Manufacturing,Midjourney,35.72,8496,2024,AdFVhenjthYSKJNzxzfaGQk wLnjRCgrHTyfXQEFjFJCMO...,18-24,Enterprise
2,Australia,Transportation,ChatGPT,13.47,8641,2024,zgNPmXBICRNbpjpTqIUWmMTeTYsInDNtAmzuxpDvcUZEAi...,45-54,Startup
3,UK,Manufacturing,ChatGPT,48.46,3488,2023,LxeKzQFbPvhxXUSgPVlLLJ pUFaicjCgiMtAmsTjovkrdE...,45-54,Enterprise
4,UK,Agriculture,Stable Diffusion,34.06,1124,2024,IOQtQoSKdSmiXRsUKpjXjXZgQohymFkVUvOASXlEnVsIOS...,45-54,SME
5,Brazil,Education,Midjourney,64.54,3267,2024,PDkHPYQGOo XqLNwpEsZlbubUVBUDBujoPCWEDoCtcwzKX...,55+,Startup
6,USA,Healthcare,Bard,81.83,4265,2023,VXo RcPqLBqywVUcwrpjmTha FxLtebijbOiZMEIYqkLEK...,35-44,Enterprise
7,Australia,Education,ChatGPT,20.85,5940,2023,MCVWNxfkdvijPwFleHKDKJTIexXAzweDWyBGDQVcOrfAsn...,25-34,Enterprise

In [12]:
display(df.info())
display(df.describe()) #statistical summary of data set- numeric

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145000 entries, 0 to 144999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   country             145000 non-null  object
 1   industry            145000 non-null  object
 2   ai_tool             145000 non-null  object
 3   adoption_rate       145000 non-null  float64
 4   daily_active_users  145000 non-null  int64
 5   year                145000 non-null  int64
 6   user_feedback       145000 non-null  object
 7   age_group           145000 non-null  object
 8   company_size        145000 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 10.0+ MB

None

       adoption_rate  daily_active_users           year
count  145000.000000       145000.000000  145000.000000
mean       49.873025         5039.302683    2023.703117
std        28.842523         2858.124918       0.456886
min         0.000000          100.000000    2023.000000
25%        24.930000         2566.000000    2023.000000
50%        49.760000         5036.000000    2024.000000
75%        74.840000         7515.000000    2024.000000
max       100.000000         9999.000000    2024.000000

### Group data

#### Subtask:
Group the data based on relevant columns to analyze relationships and trends within different categories.

**Reasoning**:
Group the DataFrame as requested in the instructions and display the head of the resulting DataFrames.

In [23]:
print("median , max , min ,var, std")

adoption_by_country = df.groupby('country')['adoption_rate'].mean().reset_index() # median , max , min ,var, std

users_by_industry_ai = df.groupby(['industry', 'ai_tool'])['daily_active_users'].sum().reset_index()

adoption_by_year_age = df.groupby(['year', 'age_group'])['adoption_rate'].mean().reset_index()

print("adoption_by_country")
display(adoption_by_country.head())

print("\nusers_by_industry_ai")
display(users_by_industry_ai.head())

print("\nadoption_by_year_age")
display(adoption_by_year_age.head())

median , max , min ,var, std
adoption_by_country

     country  adoption_rate
0  Australia      49.991022
1     Brazil      49.987023
2     Canada      49.922906
3      China      49.624838
4     France      49.785724

users_by_industry_ai

      industry           ai_tool  daily_active_users
0  Agriculture              Bard             8873755
1  Agriculture           ChatGPT            36175323
2  Agriculture            Claude             4617428
3  Agriculture        Midjourney            27186073
4  Agriculture  Stable Diffusion            13731067

adoption_by_year_age

   year age_group  adoption_rate
0  2023     18-24      49.823737
1  2023     25-34      50.098500
2  2023     35-44      50.106227
3  2023     45-54      49.880852
4  2023       55+      50.192949

In [26]:
# Show column names - RM
df.columns

Index(['country', 'industry', 'ai_tool', 'adoption_rate', 'daily_active_users',
       'year', 'user_feedback', 'age_group', 'company_size',
       'adoption_rate_qbinned'],
      dtype='object')

**Note RM**

**Python's Pandas, binning (also known as discretization)** is the process of converting continuous data into discrete intervals or bins. This is typically done using

- pd.cut()  
  - Equal-Width Binning
  - Divides the data into equal-width bin
  - Use cut() for fixed-width binning (like age groups)

- pd.qcut()
  - Quantile-Based Binning
  - Creates bins with equal number of data points (quantiles).
  - Use qcut() when you want bins with the same number of observations (like income quartiles)

  Always check bin edges with .value_counts() or .unique().

**Note RM**

**pd.cut() :** function in pandas performs binning of data, and when used for "equal-width binning," it divides a continuous variable into discrete intervals (bins) of the same width.

discrete - individually separate and distinct

**pd.qcut() :** is a Pandas function used for quantile-based discretization, also known as quantile binning. It divides a continuous variable into equal-sized bins based on the rank or sample quantiles of the data.

This means that, unlike pd.cut() which uses fixed bin edges, pd.qcut() attempts to place an approximately equal number of data points into each bin.

### Key Differences

| Feature             | `pd.cut()` (Equal Width)  | `pd.qcut()` (Quantile-Based)   |
|---------------------|----------------------------|---------------------------------|
| Bin size            | Equal range                | Equal count                     |
| Bin boundaries      | Uniformly spaced           | Based on data distribution      |
| Data distribution   | Ignored                    | Considered                      |
| Use case            | Range-based analysis       | Distribution-based analysis     |

In [40]:
# RM
# 1. pd.cut() – Equal-Width Binning
# Divides the data into equal-width bins.

import pandas as pd

# Sample data
data = pd.DataFrame({'ages': [12, 25, 37, 45, 51, 62, 73, 85]})

# Binning into 3 equal-width intervals
data['age_bins'] = pd.cut(data['ages'], bins=3)

print(data)

   ages          age_bins
0    12  (11.927, 36.333]
1    25  (11.927, 36.333]
2    37  (36.333, 60.667]
3    45  (36.333, 60.667]
4    51  (36.333, 60.667]
5    62    (60.667, 85.0]
6    73    (60.667, 85.0]
7    85    (60.667, 85.0]

**Note RM**

**bins :** number of bins or list of bin edges

**labels :** assign custom labels to bins

**right :** include the right edge (default is True)

In [36]:
# With custom labels
data['age_group'] = pd.cut(data['ages'],
                           bins=[0, 30, 60, 90],
                           labels=['Young', 'Adult', 'Senior'])
print(data)

   ages          age_bins age_group
0    12  (11.927, 36.333]     Young
1    25  (11.927, 36.333]     Young
2    37  (36.333, 60.667]     Adult
3    45  (36.333, 60.667]     Adult
4    51  (36.333, 60.667]     Adult
5    62    (60.667, 85.0]    Senior
6    73    (60.667, 85.0]    Senior
7    85    (60.667, 85.0]    Senior

In [38]:
# RM
# 2. pd.qcut() – Quantile-Based Binning
# Creates bins with equal number of data points (quantiles).

# Binning into 4 quantiles
data['quantile_bins'] = pd.qcut(data['ages'], q=4)

# With custom labels
data['quantile_group'] = pd.qcut(data['ages'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

print(data)

   ages        age_bins   quantile_bins quantile_group
0    12  (11.927, 48.5]  (11.999, 34.0]             Q1
1    25  (11.927, 48.5]  (11.999, 34.0]             Q1
2    37  (11.927, 48.5]    (34.0, 48.0]             Q2
3    45  (11.927, 48.5]    (34.0, 48.0]             Q2
4    51    (48.5, 85.0]   (48.0, 64.75]             Q3
5    62    (48.5, 85.0]   (48.0, 64.75]             Q3
6    73    (48.5, 85.0]   (64.75, 85.0]             Q4
7    85    (48.5, 85.0]   (64.75, 85.0]             Q4

### Bin data

#### Subtask:
Apply binning to numerical columns to categorize data into groups, which can be useful for frequency analysis or further grouping.

**Reasoning**:
Apply equal-width binning to the
- 'adoption_rate'
- 'daily_active_users'

columns and display the first few rows of the modified DataFrame.

In [30]:
df['adoption_rate_qbinned'] = pd.qcut(df['adoption_rate'], q=4) # 5 equal bins
#custom bins, equal bins--- equal bins-- 5

In [31]:
df[['adoption_rate','adoption_rate_qbinned']]

        adoption_rate adoption_rate_qbinned
0               40.45        (24.93, 49.76]
1               35.72        (24.93, 49.76]
2               13.47       (-0.001, 24.93]
3               48.46        (24.93, 49.76]
4               34.06        (24.93, 49.76]
...               ...                   ...
144995          86.93        (74.84, 100.0]
144996          51.99        (49.76, 74.84]
144997          47.35        (24.93, 49.76]
144998          31.87        (24.93, 49.76]
144999          96.84        (74.84, 100.0]

[145000 rows x 2 columns]

In [32]:
df['adoption_rate_qbinned'].value_counts()

adoption_rate_qbinned
(24.93, 49.76]     36254
(-0.001, 24.93]    36251
(49.76, 74.84]     36248
(74.84, 100.0]     36247
Name: count, dtype: int64

In [41]:
# min and max
print(df['adoption_rate'].min())
print(df['adoption_rate'].max())

0.0
100.0

In [47]:
df['adoption_rate_binned'] = pd.cut(df['adoption_rate'], bins=[-0.001,20,40,50,120], labels=['low','medium','high','very high']) # 5 equal bins
df[['adoption_rate','adoption_rate_binned',"country"]]

        adoption_rate adoption_rate_binned    country
0               40.45                 high        USA
1               35.72               medium     France
2               13.47                  low  Australia
3               48.46                 high         UK
4               34.06               medium         UK
...               ...                  ...        ...
144995          86.93            very high  Australia
144996          51.99            very high    Germany
144997          47.35                 high        USA
144998          31.87               medium        USA
144999          96.84            very high     Canada

[145000 rows x 3 columns]

In [48]:
df['adoption_rate_binned'] .value_counts()

adoption_rate_binned
very high    72167
medium       29192
low          29103
high         14538
Name: count, dtype: int64

In [49]:
df['adoption_rate'] .value_counts()

adoption_rate
33.09    31
53.43    29
33.81    29
49.25    28
44.27    28
         ..
89.99     4
70.66     3
36.04     3
64.30     3
26.81     3
Name: count, Length: 10001, dtype: int64

## Summary:

### Data Analysis Key Findings

*   The dataset contains 145,000 entries and 9 columns, including 'country', 'industry', 'ai\_tool', 'adoption\_rate', 'daily\_active\_users', 'year', 'user\_feedback', 'age\_group', and 'company\_size'.

*   The data types include float64 for 'adoption\_rate', int64 for 'daily\_active\_users' and 'year', and object for the remaining columns.

*   The average AI adoption rate varies by country, industry, and age group over the years.

*   The total number of daily active users for AI tools varies across different industries.

*   New columns, 'adoption\_rate\_binned' and 'daily\_active\_users\_binned', were added by categorizing the original numerical columns into bins.

### Insights or Next Steps

*   Further analysis could involve visualizing the average adoption rates by country and year to identify trends or significant shifts.

*   Investigating the relationship between 'user\_feedback' and 'adoption\_rate' or 'daily\_active\_users' could provide insights into user satisfaction and its impact on AI tool usage.

In [50]:
# Show column names - RM
df.columns

Index(['country', 'industry', 'ai_tool', 'adoption_rate', 'daily_active_users',
       'year', 'user_feedback', 'age_group', 'company_size',
       'adoption_rate_qbinned', 'adoption_rate_binned'],
      dtype='object')

In [51]:
# Show general info (data types, non-null counts) - RM
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145000 entries, 0 to 144999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                145000 non-null  object
 1   industry               145000 non-null  object
 2   ai_tool                145000 non-null  object
 3   adoption_rate          145000 non-null  float64
 4   daily_active_users     145000 non-null  int64
 5   year                   145000 non-null  int64
 6   user_feedback          145000 non-null  object
 7   age_group              145000 non-null  object
 8   company_size           145000 non-null  object
 9   adoption_rate_qbinned  145000 non-null  category
 10  adoption_rate_binned   145000 non-null  category
dtypes: category(2), float64(1), int64(2), object(6)
memory usage: 10.2+ MB